= OPS09-BP01 Identify key performance indicators

Identify key performance indicators (KPIs) based on desired business outcomes (for example, new features delivered) and customer outcomes (for example, customer support cases). Evaluate KPIs to determine operations success.

Common anti-patterns::

- You are asked by business leadership how successful operations is at accomplishing business goals but have no frame of reference to determine success.

- You are unable to determine if your maintenance windows have an impact on business outcomes.

Benefits of establishing this best practice:: By identifying key performance indicators you enable achieving business outcomes as the test of the health and success of your operations.

Level of risk exposed if this best practice is not established:: High

== Implementation guidance

Identify key performance indicators: Identify key performance indicators (KPIs) based on desired business and customer outcomes. Evaluate KPIs to determine operations success.
