= OPS08-BP04 Establish workload metrics baselines

Establish baselines for metrics to provide expected values as the basis #for comparison and identification of under- and over-performing components#. Identify thresholds for improvement, investigation, and intervention.

Common anti-patterns::

- A server is running at 95% CPU utilization you are asked if that is good or bad. CPU utilization on that server has not been baselined so you have no idea if that is good or bad.

Benefits of establishing this best practice:: By defining baseline metric values you are able to evaluate current metric values, and metric trends, to determine if action is required.

Level of risk exposed if this best practice is not established:: Medium

== Implementation guidance

Establish baselines for workload metrics: Establish baselines for workload metrics to provide expected values as the basis for comparison.

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html[Creating Amazon CloudWatch Alarms]
