= OPS08-BP03 Collect and analyze workload metrics

Perform regular proactive reviews of metrics to identify trends and determine where appropriate responses are needed.

You should aggregate log data from your application, workload components, services, and API calls to a service such as CloudWatch Logs. Generate metrics from observations of necessary log content to enable insight into the performance of operations activities.

Common anti-patterns::

- You are asked by the network design team for current network bandwidth utilization rates. You provide the current metrics, network utilization is at 35%. They reduce circuit capacity as a cost savings measure causing widespread connectivity issues as your point-in-time measurement did not reflect the trend in utilization rates.

- Your router has failed. It has been logging non-critical memory errors with greater and greater frequency up until its complete failure. You did not detect this trend and as a result did not replace the faulty memory before the router caused a service interruption.

Benefits of establishing this best practice:: By collecting and analyzing your workload metrics you gain understanding of the health of your workload and can gain insight to trends that may have an impact on your workload or the achievement of your business outcomes.

Level of risk exposed if this best practice is not established:: High

== Implementation guidance

Collect and analyze workload metrics: Perform regular proactive reviews of metrics to identify trends and determine where appropriate responses are needed.

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/working_with_metrics.html[Using Amazon CloudWatch metrics]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CW_Support_For_AWS.html[Amazon CloudWatch metrics and dimensions reference]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html[Collect metrics and logs from Amazon EC2 instances and on-premises servers with the CloudWatch Agent]


