= OPS08-BP02 Define workload metrics

Define workload metrics to measure the achievement of KPIs (for example, abandoned shopping carts, orders placed, cost, price, and allocated workload expense). Define workload metrics to measure the health of the workload (for example, interface response time, error rate, requests made, requests completed, and utilization). Evaluate metrics to determine if the workload is achieving desired outcomes, and to understand the health of the workload.

You should send log data to a service such as CloudWatch Logs, and generate metrics from observations of necessary log content.

CloudWatch has specialized features such as Amazon CloudWatch Insights for .NET and SQL Server and Container Insights that can assist you by identifying and setting up key metrics, logs, and alarms across your specifically supported application resources and technology stack.

Common anti-patterns::

- You have defined standard metrics, not associated to any KPIs or tailored to any workload.

- You have errors in your metrics calculations that will yield invalid results.

- You don't have any metrics defined for your workload.

- You only measure for availability.

Benefits of establishing this best practice:: By defining and evaluating workload metrics you can determine the health of your workload and measure the achievement of business outcomes.

Level of risk exposed if this best practice is not established:: High

== Implementation guidance
Define workload metrics: Define workload metrics to measure the achievement of KPIs. Define workload metrics to measure the health of the workload and its individual components. Evaluate metrics to determine if the workload is achieving desired outcomes, and to understand the health of the workload.

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html[Publish custom metrics]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html[Searching and filtering log data]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CW_Support_For_AWS.html[Amazon CloudWatch metrics and dimensions reference]
