= OPS09-BP02 Define operations metrics

Define operations metrics to measure the achievement of KPIs (for example, successful deployments, and failed deployments). Define operations metrics to measure the health of operations activities (for example, mean time to detect an incident (MTTD), and mean time to recovery (MTTR) from an incident). Evaluate metrics to determine if operations are achieving desired outcomes, and to understand the health of your operations activities.

Common anti-patterns::

- Your operations metrics are based on what the team thinks is reasonable.

- You have errors in your metrics calculations that will yield incorrect results.

- You don't have any metrics defined for your operations activities.

Benefits of establishing this best practice:: By defining and evaluating operations metrics you can determine the health of your operations activities and measure the achievement of business outcomes.

Level of risk exposed if this best practice is not established:: High

== Implementation guidance

Define operations metrics: Define operations metrics to measure the achievement of KPIs. Define operations metrics to measure the health of operations and its activities. Evaluate metrics to determine if operations are achieving desired outcomes, and to understand the health of the operations.

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html[Publish custom metrics]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html[Searching and filtering log data]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CW_Support_For_AWS.html[Amazon CloudWatch metrics and dimensions reference]


