= Understanding operational health

Define, capture, and analyze operations metrics to gain visibility to workload events so that you can take appropriate action.

Your team should be able to understand the health of your operations easily. You will want to use metrics based on operations outcomes to gain useful insights. You should use these metrics to implement dashboards with business and technical viewpoints that will help team members make informed decisions.

AWS makes it easier to bring together and analyze your operations logs so that you can generate metrics, know the status of your operations, and gain insight from operations over time.

== Best Practices
. Identify key performance indicators
. xref:OPS09-BP02.adoc[Define operations metrics]
. Collect and analyze operations metrics
. Establish operations metrics baselines
. Learn the expected patterns of activity for operations
. Alert when operations outcomes are at risk
. Alert when operations anomalies are detected
. Validate the achievement of outcomes and the effectiveness of KPIs and metrics