= OPS04-BP02 Implement and configure workload telemetry

Design and configure your workload to emit information about its internal state and current status, for example, API call volume, HTTP status codes, and scaling events. Use this information to help determine when a response is required.

Use a service such as Amazon CloudWatch to aggregate logs and metrics from workload components (for example, API logs from AWS CloudTrail, AWS Lambda metrics, Amazon VPC Flow Logs, and other services).

Common anti-patterns::

- Your customers are complaining about poor performance. There are no recent changes to your application and so you suspect an issue with a workload component. You have no telemetry to analyze to determine what component or components are contributing to the poor performance.

- Your application is unreachable. You lack the telemetry to determine if it's a networking issue.

Benefits of establishing this best practice:: Understanding what is going on inside your workload enables you to respond if necessary.

Level of risk exposed if this best practice is not established:: High

== Implementation guidance
* Implement log and metric telemetry: Instrument your workload to emit information about its internal state, status, and the achievement of business outcomes. Use this information to determine when a response is required.

- https://youtu.be/1Ck_me4azMw[Gaining better observability of your VMs with Amazon CloudWatch - AWS Online Tech Talks]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_architecture.html[How Amazon CloudWatch works]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html[What is Amazon CloudWatch?]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/working_with_metrics.html[Using Amazon CloudWatch metrics]

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html[What is Amazon CloudWatch Logs?]

** Implement and configure workload telemetry: Design and configure your workload to emit information about its internal state and current status (for example, API call volume, HTTP status codes, and scaling events).

*** https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CW_Support_For_AWS.html[Amazon CloudWatch metrics and dimensions reference]

*** http://aws.amazon.com/cloudtrail/[AWS CloudTrail]

*** https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html[What Is AWS CloudTrail?]

*** https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html[VPC Flow Logs]
