= OPS05-BP03 Use configuration management systems

Use configuration management systems to make and track configuration changes. These systems reduce errors caused by manual processes and reduce the level of effort to deploy changes.

Static configuration management sets values when initializing a resource that are expected to remain consistent throughout the resource’s lifetime. Some examples include setting the configuration for a web or application server on an instance, or defining the configuration of an AWS service within the AWS Management Console or through the AWS CLI.

Dynamic configuration management sets values at initialization that can or are expected to change during the lifetime of a resource. For example, you could set a feature toggle to enable functionality in your code via a configuration change, or change the level of log detail during an incident to capture more data and then change back following the incident eliminating the now unnecessary logs and their associated expense.

If you have dynamic configurations in your applications running on instances, containers, serverless functions, or devices, you can use https://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfig.html[AWS AppConfig] to manage and deploy them across your environments.

On AWS, you can use https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html[AWS Config] to continuously monitor your AWS resource configurations across accounts and Regions. It enables you to track their configuration history, understand how a configuration change would affect other resources, and audit them against expected or desired configurations using https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config.html[AWS Config Rules] and https://docs.aws.amazon.com/config/latest/developerguide/conformance-packs.html[AWS Config Conformance Packs].

On AWS, you can build continuous integration/continuous deployment (CI/CD) pipelines using services such as AWS Developer Tools (for example, AWS CodeCommit, AWS CodeBuild, AWS CodePipeline, AWS CodeDeploy, and AWS CodeStar ).

Have a change calendar and track when significant business or operational activities or events are planned that may be impacted by implementation of change. Adjust activities to manage risk around those plans. https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-change-calendar.html[AWS Systems Manager Change Calendar] provides a mechanism to document blocks of time as open or closed to changes and why, and share that information with other AWS accounts. AWS Systems Manager Automation scripts can be configured to adhere to the change calendar state.

https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-maintenance.html[AWS Systems Manager Maintenance Windows] can be used to schedule the performance of AWS SSM Run Command or Automation scripts, AWS Lambda invocations, or AWS Step Functions activities at specified times. Mark these activities in your change calendar so that they can be included in your evaluation.

Common anti-patterns::

- You manually update the web server configuration across your fleet and a number of servers become unresponsive due to update errors.

- You manually update your application server fleet over the course of many hours. The inconsistency in configuration during the change causes unexpected behaviors.

- Someone has updated your security groups and your web servers are no longer accessible. Without knowledge of what was changed you spend significant time investigating the issue extending your time to recovery.

Benefits of establishing this best practice:: Adopting configuration management systems reduces the level of effort to make and track changes, and the frequency of errors caused by manual procedures.

Level of risk exposed if this best practice is not established:: Medium

== Implementation guidance
 Use configuration management systems: Use configuration management systems to track and implement changes, to reduce errors caused by manual processes, and reduce the level of effort.