= OPS07-BP01 Ensure personnel capability

Have a mechanism to validate that you have the appropriate number of trained personnel to provide support for operational needs. Train personnel and adjust personnel capacity as necessary to maintain effective support.

You will need to have enough team members to cover all activities (including on-call). Ensure that your teams have the necessary skills to be successful with training on your workload, your operations tools, and AWS.

Common anti-patterns::

- Deploying a workload without team members skilled to support the platform and services in use.

- Deploying a workload without team members available during intended hours of support.

- Deploying a workload without sufficient team members to support it if there are team members on leave or out sick.

- Deploying additional workloads without reviewing the additional impact on team members support it and other workloads.

Benefits of establishing this best practice:: Having skilled team members enables effective support of your workload.

Level of risk exposed if this best practice is not established:: High

== Implementation guidance

Personnel capability: Validate that there are sufficient trained personnel to effectively support the workload.

- Team size: Ensure that you have enough team members to cover operational activities, including on-call duties.

- Team skill: Ensure that your team members have sufficient training on AWS, your workload, and your operations tools to perform their duties.

* http://aws.amazon.com/about-aws/events/[AWS Events and Webinars]

* http://aws.amazon.com/training/[Welcome to AWS Training and Certification]

- Review capabilities: Review team size and skill as operating conditions and workloads change, to ensure there is sufficient capability to maintain operational excellence. Make adjustments to ensure that team size and skill match the operational requirements for the workloads that the team supports.
