= Storage solution for AKS

== Readings
[example]
=====
* https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-storage#choose-the-appropriate-storage-type[Best practices for storage and backups in Azure Kubernetes Service (AKS)]
* https://medium.com/codex/mounting-azure-files-and-blobs-using-non-traditional-options-in-kubernetes-e12b1522f14f
=====

== Azure Blobs as volumes

=== Azure Blob Storage https://github.com/kubernetes-sigs/blob-csi-driver[CSI driver]

csi plugin name: `blob.csi.azure.com`

==== Install Azure Blob Storage CSI driver on a Kubernetes cluster
See document https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/install-blob-csi-driver.md[Install Azure Blob Storage CSI driver on a Kubernetes cluster]

===== v1.11.0
https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/install-csi-driver-v1.11.0.md

====== Install with kubectl

Remote Install::
+
[source]
----
curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/v1.11.0/deploy/install-driver.sh | bash -s v1.11.0 blobfuse-proxy --
----

Local Install::
+
[source, bash]
----
git clone https://github.com/kubernetes-sigs/blob-csi-driver.git
cd blob-csi-driver
./deploy/install-driver.sh v1.11.0 local,blobfuse-proxy
----

====== check pods status

[source, bash]
----
kubectl -n kube-system get pod -o wide -l app=csi-blob-controller
kubectl -n kube-system get pod -o wide -l app=csi-blob-node
----

==== Installation on AKS

TIP: See details at Set up CSI driver on https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/install-driver-on-aks.md[AKS cluster]

. Setup right permissions
.. Grant `Contributor` role to the user assigned identity (i.e.: _aks-map-westeurope-agentpool_) for the node resource group (i.e.: _rg-aks-nodes-map-westeurope_) in the target AKS cluster
.. The same user assigned identity (i.e.: _aks-map-westeurope-agentpool_) needs to be granted `Storage Account Key Operator Service Role` for the target storage account so that the SAS key can be fetched silently at runtime.
. https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/install-blob-csi-driver.md[Install CSI driver]
. Set up new storage classes
+
[source]
----
kubectl create -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/example/storageclass-blobfuse.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/example/storageclass-blob-nfs.yaml
----

==== Examples
StorageClass::
+
[source,yaml]
----
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-source-map-data
provisioner: blob.csi.azure.com
parameters:
  resourceGroup: rg-map-delivery-westeurope
  storageAccount: mapdeliveryinternalweu
  containerName: source-map
  # server: SERVER_ADDRESS  # optional, provide a new address to replace default "accountname.blob.core.windows.net"
reclaimPolicy: Retain  # if set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=60  # prevent billing charges on mounting
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.
----

PVC::
+
[source,yaml]
----
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-source-map
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: blob-source-map-data
----
Pod::
+
[source, yaml]
----
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-blob
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      name: nginx-blob
      command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/blob/outfile; sleep 1; done
      volumeMounts:
        - name: blob01
          mountPath: "/mnt/blob"
  volumes:
    - name: blob01
      persistentVolumeClaim:
        claimName: pvc-blob-source-map

----
