= Secrets Store CSI Driver
:toc:


Secrets Store CSI Driver for Kubernetes secrets - Integrates secrets stores with Kubernetes via a Container Storage Interface (CSI) volume.

The Secrets Store CSI Driver secrets-store.csi.k8s.io allows Kubernetes to mount multiple secrets, keys, and certs stored in enterprise-grade external secrets stores into their pods as a volume. Once the Volume is attached, the data in it is mounted into the container’s file system.

.References
[sidebar]
****
* https://secrets-store-csi-driver.sigs.k8s.io
* https://azure.github.io/secrets-store-csi-driver-provider-azure/
* https://github.com/hashicorp/vault-csi-provider
****

== Secrets Store CSI Driver

- https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage.html[Usage]
- https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html[Sync as Kubernetes Secret]


== Azure Secrets store for key vault

=== AKS setup
- https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver[Use the Azure Key Vault Provider for Secrets Store CSI Driver in an AKS cluster]
- https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access[Provide an identity to access the Azure Key Vault Provider for Secrets Store CSI Driver]

=== Azure Key Vault Provider for Secrets Store CSI Driver
- https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/usage/[Using the Azure Key Vault Provider]
- https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/[Configurations]
- https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/sync-with-k8s-secrets/[Sync Mounted Content with Kubernetes Secret]

== Create `SecretProviderClass` in Kubernetes

=== Kubernetes manifest

[source,yaml]
----
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-credentials
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: foosecret
      type: Opaque
      labels:
        environment: "test"
      data:
        - objectName: taClientSecret                    # name of the mounted content to sync. this could be the object name or object alias
          key: taSecret
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 281560cf-6725-4760-b34d-19819ec62b9f
    keyvaultName: kv-app-platform
    objects:  |
      array:
        - |
          objectName: ta-ClientSecret
          objectAlias: taClientSecret
          objectType: secret
        - |
          objectName: shared-storageAccountAccessKey
          objectType: secret
    tenantId: <your-tenant-id>
----

=== Terraform resource

[source, hcl-terraform]
----
resource "kubernetes_manifest" "spc_app_credentials" {
  manifest = {
    "apiVersion" = "secrets-store.csi.x-k8s.io/v1"
    "kind"       = "SecretProviderClass"
    "metadata"   = {
      "name"      = "app-credentials"
      "namespace" = kubernetes_namespace.app_platform.metadata[0].name
    }
    spec = {
      provider      = "azure"
      secretObjects = [
        {
          secretName = "kv-app-credentials"
          type       = "Opaque"
          labels     = {
            "app.kubernetes.io/created-by" = "terraform"
            "app.kubernetes.io/part-of"    = "app-platform"
            "app.kubernetes.io/component"  = "configuration"
          }
          data = [
            {
              objectName = "taClientSecret"
              key        = "taSecret"
            }
          ]
        }
      ]
      parameters = {
        tenantId               = data.azurerm_client_config.current.tenant_id
        useVMManagedIdentity   = "true"
        userAssignedIdentityID = data.azurerm_user_assigned_identity.keyvault_secrets_provider.client_id
        keyvaultName           = data.azurerm_key_vault.app_platform.name
        objects                = <<-EOF
        array:
          - |
            objectName: ta-ClientSecret
            objectAlias: taClientSecret
            objectType: secret
          - |
            objectName: shared-storageAccountAccessKey
            objectType: secret
        EOF
      }
    }
  }
}
----

== Use the `SecretProviderClass` class

=== Use as environment variable

[source, yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-csi
  name: nginx-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-csi
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-csi
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: foosecret
                key: taSecret

        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        resources:
          requests:
            memory: 100Mi
            cpu: 200m
          limits:
            memory: 150Mi
            cpu: 1
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "app-credentials"

----
