= SRE Culture & discipline
:toc: 

== Learning Resources

[cols="40,60"]
|===
|Resource|Description

|https://github.com/upgundecha/howtheysre[How They SRE]
|*How They SRE* is a curated knowledge repository of best practices, tools, techniques, and culture of SRE adopted by the leading technology or tech-savvy organizations.

|https://www.blameless.com/sre/top-predictions-for-sre-2021[Here are the Top Predictions for SRE in 2021]
|

|https://www.getambassador.io/resources/rise-of-cloud-native-engineering-organizations/[SRE vs. Platform Engineering]
|DevOps, GitOps, and the Rise of Cloud-Native Engineering

|https://about.gitlab.com/handbook/engineering/infrastructure/team/reliability/[Gitlab Reliability Engineering]
| Gitlab SRE public documentation

|https://jaychapel.medium.com/should-your-company-adopt-googles-site-reliability-engineering-approach-3eacd8d1aaa3[Should Your Company Adopt Google’s Site Reliability Engineering Approach?]
|


|===


== Toil/Automation

One of the benefits of using an orchestration system like Kubernetes and a managed Kubernetes offering like AKS, EKS, GKE etc is that much of the tedious tasks that Operations traditionally had to perform have been automated away e.g. Application Auto-scaling (HPA and VPA), Node Scaling (Cluster Auto-scaler), Control Plane and Node Upgrades, Pod Disruption Budgets. Add in some community addons such as Velero, and you get other operations tasks like backups already automated. Others like Prometheus give you the ability to monitor your clusters.

So what else does the SRE have to automate? Well they automate for reliability. Let’s look at an example.

Let’s say we’re using a managed cluster and their cluster upgrade process. We’re sometimes seeing cluster upgrade failures, which means the SRE gets pinged to investigate, taking them away from their automation work. The upgrade failures have been attributed to a number of reasons

. Not enough IP’s left in the clusters CIDR block to perform an . autoscaling group/nodepool upgrade
. Unrealistic PDB’s set which can never be achieved i.e. maxUnavailable set to 0
. K8s API’s removed
. Pods with no Replica Set
Once the SRE has identified the toil (the work that takes them away from their automation), they can get to work on automation to carry out a number of pre flight checks, before an upgrade even starts. Only if the pre flight checks complete successfully, then can an upgrade start.

The SRE should aim to spend 50% of their time on regular Ops work and 50% automating away toil. If the regular Ops work is taking up more than 50% then more resources should be scheduled to help, until some of the toil has been automated away.