= Azure application architecture fundamentals
:toc:
:icons: font
:source-highlighter: rouge
:imagesdir: ./images


.Readings
****
* https://docs.microsoft.com/en-us/azure/architecture/architectures/?filter=reference-architecture[Azure Reference architectures]
* https://docs.microsoft.com/en-us/azure/architecture/guide/design-principles/[Design principles]
* https://docs.microsoft.com/en-us/azure/architecture/patterns/[Design patterns]
* https://docs.microsoft.com/en-us/azure/architecture/best-practices[Best practices]
* https://docs.microsoft.com/en-us/security/compass/applications-services[Security best practices]
****


== Introduction

image::https://docs.microsoft.com/en-us/azure/architecture/guide/images/a3g.svg[]

=== Architecture styles

The first decision point is the most fundamental. What kind of architecture are you building? It might be a microservices architecture, a more traditional N-tier application, or a big data solution. We have identified several distinct architecture styles. There are benefits and challenges to each.

=== Technology choices
Knowing the type of architecture you are building, now you can start to choose the main technology pieces for the architecture. The following technology choices are critical:

* _Compute_ refers to the hosting model for the computing resources that your applications run on. For more information, see Choose a compute service.

* _Data stores_ include databases but also storage for message queues, caches, logs, and anything else that an application might persist to storage. For more information, see Choose a data store.

* _Messaging_ technologies enable asynchronous messages between components of the system. For more information, see Choose a messaging service.

You will probably have to make additional technology choices along the way, but these three elements (compute, data, and messaging) are central to most cloud applications and will determine many aspects of your design.

=== Design the architecture

Once you have chosen the architecture style and the major technology components, you are ready to tackle the specific design of your application.
