= Control Groups (`cgroups`)
:toc:

.References
[sidebar]
****
* https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/index.html[Control Groups version 1]
* https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html[Control Group v2]
* https://man7.org/linux/man-pages/man7/cgroups.7.html[cgroups(7) — Linux manual page]
* https://medium.com/@kasunmaduraeng/docker-namespace-and-cgroups-dece27c209c7[Docker Namespace and Cgroups]
* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/resource_management_guide/sec-default_cgroup_hierarchies[DEFAULT CGROUP HIERARCHIES]
* https://opensource.com/article/20/10/cgroups[Managing resources with cgroups in systemd]
* https://wiki.archlinux.org/title/cgroups
****

== Introduction
_Cgroups_ provide resource limitation and reporting capability within the container space. They allow granular control over what host resources are allocated to the containers and when they are allocated.

Control groups can be accessed with various tools:

* using directives in systemd unit files to specify limits for services and slices;
* by accessing the cgroup filesystem directly;
* via tools like cgcreate, cgexec and cgclassify (part of the libcgroupAUR and libcgroup-gitAUR packages);
* using the "rules engine daemon" to automatically move certain users/groups/commands to groups (`/etc/cgrules.conf` and `/usr/lib/systemd/system/cgconfig.service`) (part of the libcgroupAUR and libcgroup-gitAUR packages); and
* through other software such as Linux Containers (LXC) virtualization.
* cgmanager is deprecated and unsupported as it does not work with systemd versions 232 and above.

=== Common control groups

. CPU
. Memory
. Network Bandwidth
. Disk
. Priority

== Using cgroups

=== Find cgroups info
[source, bash]
----
sudo systemd-cgls
sudo systemd-ctop
----

=== Use cgroups with docker
Using these cgroup policies is very simple. If you for instance want to lock down a Docker container to the first CPU core, you’d append --cpuset-cpus=0 to your docker run command.And also you could setup the cpu shares which you required.

[source, bash]
====
$ docker run -d --name='kasun_priority_1' --cpuset-cpus=0 --cpu-shares=20 kasuntest1

$ docker run -d --name='kasun_priority_2' --cpuset-cpus=2 --cpu-shares=30 kasuntest2
====

And we could use the below command to change running container CPU shards.

    sudo systemctl set-property docker-7d7ds9s7dhdsda044b29cb873cac460b429cfcbdd0e877c0868eb2a901dbf80.scope CPUShares=512

