= Incident Management
:toc: auto
:icons: font
:imagesdir: ./images

== When to Declare an Incident

=== Broad guidelines
If any of the following is true, the event is an incident:

- Do you need to involve a second team in fixing the problem?
- Is the outage visible to customers?
- Is the issue unsolved even after an hour’s concentrated analysis?


== Best Practices for Incident Management

Prioritize.:: Stop the bleeding, restore service, and perserve the evidence for root-causing.

Prepare.:: Develop and document your incident management procedures in advance, in consultation with incident participants.
Trust.:: Give full autonomy within the assigned role to all incident participants. Introspect. Pay attention to your emotional state while responding to an incident. If you start to feel panicky or overwhelmed, solicit more support.
Consider alternatives.:: Periodically consider your options and re-evaluate whether it still makes sense to continue what you’re doing or whether you should be taking another tack in incident response.
Practice.:: Use the process routinely so it becomes second nature.
Change it around.:: Were you incident commander last time? Take on a different role this time. Encourage every team member to acquire familiarity with each role.