spring:
  output.ansi.enabled: DETECT
  cloud:
    stream:
      function.definition: eventListener;demoListener
      bindings:
        demoListener-in-0:
          destination: demo-events
          group: demo-listeners
        eventListener-in-0:
          destination: app-events
          group: event-handler
      poller:
        initial-delay: 0
        fixed-delay: 1000

################################################################################
#
#    Observability settings - can be shared across applications
#
################################################################################
otel:
  propagation:
    type: tracecontext
  instrumentation:
    spring-integration:
      producer:
        enabled: true
    spring-webflux:
      experimental-span-attributes: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true

logging:
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSXXX,UTC
    console: "%clr(%d{${logging.pattern.dateformat}}){faint} %clr(%5p) %clr([%X{trace_id},%X{span_id},%X{trace_flags}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.20t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"