= Practice Cloud Financial Management
:toc:
:imagesdir: ./images
:icons: font

Cloud Financial Management (CFM) enables organizations to realize business value and financial success as they optimize their cost and usage and scale on AWS.

== Functional Ownership
Establish a cost optimization function:: This function is responsible for establishing and maintaining a culture of cost awareness. It can be an existing individual, a team within your organization, or a new team of key finance, technology and organization stakeholders from across the organization.

The function requires a multi-disciplined approach, with capabilities in project management, data science, financial analysis, and software/infrastructure development. The function can improve efficiencies of workloads by executing cost optimizations (centralized approach), influencing technology teams to execute optimizations (decentralized), or a combination of both (hybrid). The function may be measured against their ability to execute and deliver against cost optimization goals (for example, workload efficiency metrics).

You must secure executive sponsorship for this function. The sponsor is regarded as champion for cost efficient cloud consumption, and provides escalation support for the function to ensure that cost optimization activities are treated with the level of priority defined by the organization. Together, the sponsor and function ensure that your organization consumes the cloud efficiently and continue to deliver business value.

[IMPORTANT]
====
Just like project management, this effort is to get sponsorship from higher management (CFO/Finance Team) to have the right authority and support.

Usually, the cloud infra team (SRE/IT Infra) can manage to get the most detailed cloud resource usage information. But team level details rely on excessive usage of tagging for cloud resources and labelling for Kubernetes resources if Kubernetes is _THE_ platform for running workloads.
====

== Finance and Technology Partnership
Establish a partnership between key finance and technology stakeholders to create a shared understanding of organizational goals and develop mechanisms to succeed financially in the variable spend model of cloud computing. Relevant teams within your organization must be involved in cost and usage discussions at all stages of your cloud journey, including:

* *Financial leads*: CFOs, financial controllers, financial planners, business analysts, procurement, sourcing, and accounts payable must understand the cloud model of consumption, purchasing options, and the monthly invoicing process. Due to the fundamental differences between the cloud (such as the rate of change in usage, pay as you go pricing, tiered pricing, pricing models, and detailed billing and usage information) compared to on-premises operation, it is essential that the finance organization understands how cloud usage can impact business aspects including procurement processes, incentive tracking, cost allocation and financial statements.

* *Technology leads*: Technology leads (including product and application owners) must be aware of the financial requirements (for example, budget constraints) as well as business requirements (for example, service level agreements). This allows the workload to be implemented to achieve the desired goals of the organization.

The partnership of finance and technology provides the following benefits:

- Finance and technology teams have near real-time visibility into cost and usage.

- Finance and technology teams establish a standard operating procedure to handle cloud spend variance.

- Finance stakeholders act as strategic advisors with respect to how capital is used to purchase commitment discounts (for example, Reserved Instances or AWS Savings Plans), and how the cloud is used to grow the organization.

- Existing accounts payable and procurement processes are used with the cloud.

- Finance and technology teams collaborate on forecasting future AWS cost and usage to align/build organizational budgets.

- Better cross-organizational communication through a shared language, and common understanding of financial concepts.

== Cost-Aware Processes

=== Report and notify on cost and usage optimization
You must regularly report on cost and usage optimization within your organization. You can implement dedicated sessions to cost optimization, or include cost optimization in your regular operational reporting cycles for your workloads. https://aws.amazon.com/aws-cost-management/aws-cost-explorer/[AWS Cost Explorer] provides dashboards and reports. You can track your progress of cost and usage against configured budgets with http://aws.amazon.com/about-aws/whats-new/2019/07/introducing-aws-budgets-reports/[AWS Budgets Reports].

You can also use http://aws.amazon.com/quicksight/[Amazon QuickSight] with Cost and Usage Report (CUR) data, to provide highly customized reporting with more granular data.

Implement notifications on cost and usage to ensure that changes in cost and usage can be acted upon quickly. http://aws.amazon.com/aws-cost-management/aws-budgets/[AWS Budgets] allows you to provide notifications against targets. We recommend configuring notifications on both increases and decreases, and in both cost and usage for workloads.

=== Monitor cost and usage proactively
It is recommended to monitor cost and usage proactively within your organization, not just when there are exceptions or anomalies. Highly visible dashboards throughout your office or work environment ensure that key people have access to the information they need, and indicate the organization’s focus on cost optimization. Visible dashboards enable you to actively promote successful outcomes and implement them throughout your organization.
