= Cost Effective Resources
:toc:
:icons: font
:imagesdir: ./images

== Managed Services

Managed services remove the operational and administrative burden of maintaining a service, which allows you to focus on innovation. Additionally, because managed services operate at cloud scale, they can offer a lower cost per transaction or service.

Consider the time savings that will allow your team to focus on retiring technical debt, innovation, and value-adding features. For example, you might need to “lift and shift” your on-premises environment to the cloud as rapidly as possible and optimize later. It is worth exploring the savings you could realize by using managed services that remove or reduce license costs.

Usually, managed services have attributes that you can set to ensure sufficient capacity. You must set and monitor these attributes so that your excess capacity is kept to a minimum and performance is maximized. You can modify the attributes of AWS Managed Services using the AWS Management Console or AWS APIs and SDKs to align resource needs with changing demand. For example, you can increase or decrease the number of nodes on an Amazon EMR cluster (or an Amazon Redshift cluster) to scale out or in.

You can also pack multiple instances on an AWS resource to enable higher density usage. For example, you can provision multiple small databases on a single Amazon Relational Database Service (Amazon RDS) DB instance. As usage grows, you can migrate one of the databases to a dedicated RDS DB instance using a snapshot and restore process.

When provisioning workloads on managed services, you must understand the requirements of adjusting the service capacity. These requirements are typically time, effort, and any impact to normal workload operation. The provisioned resource must allow time for any changes to occur, provision the required overhead to allow this. The ongoing effort required to modify services can be reduced to virtually zero by using APIs and SDKs that are integrated with system and monitoring tools, such as Amazon CloudWatch.

Amazon Relational Database Service (RDS), Amazon Redshift, and Amazon ElastiCache provide a managed database service. Amazon Athena, Amazon Elastic Map Reduce (EMR), and Amazon OpenSearch Service provide a managed analytics service.

http://aws.amazon.com/managed-services/[AWS Managed Services (AMS)] is a service that operates AWS infrastructure on behalf of enterprise customers and partners. It provides a secure and compliant environment that you can deploy your workloads onto. AMS uses enterprise cloud operating models with automation to allow you to meet your organization requirements, move into the cloud faster, and reduce your on-going management costs.

=== Select the Correct Resource Type, Size, and Number
In AWS, there are a number of different approaches:

- Perform cost modeling
- Select size based on metrics or data
- Select size automatically (based on metrics)

=== Select the Best Pricing Model

AWS has multiple http://aws.amazon.com/pricing/[pricing models] that allow you to pay for your resources in the most cost-effective way that suits your organization’s needs. The following section describes each purchasing model:

- On-Demand

- Spot

- Commitment discounts - Savings Plans

- Commitment discounts - Reserved Instances/Capacity

- Geographic selection

- Third-party agreements and pricing

=== Plan for Data Transfer
