= Monitoring
:toc: auto

== Metrics Definition

=== The Four Golden Signals
Google gave us a place to start in the excellent SRE Handbook with the notion of the “Four Golden Signals”:

[quote]
____
The four golden signals of monitoring are latency, traffic, errors, and saturation. If you can only measure four metrics of your user-facing system, focus on these four.

Latency:: The time it takes to service a request
Traffic:: A measure of how much demand is being placed on your system
Errors:: The rate of requests that fail
Saturation:: How “full” your service is.
____

=== The USE Method
http://www.brendangregg.com/usemethod.html

Brendan Gregg does http://www.brendangregg.com/usemethod.html[an excellent job] explaining how to think about Utilization, Saturation and Errors when looking at the resources in your system.

He gives the following definitions:

[quote]
____
Resource: all physical server functional components (CPUs, disks, busses, …)

Utilization:: the average time that the resource was busy servicing work
Saturation:: the degree to which the resource has extra work which it can’t service, often queued
Errors:: the count of error events
____
He suggests, but does not prescribe, exactly which metrics that represent utilization, saturation and errors in the context of a Unix system. The rest of this article I will apply the USE method to resources in your Kubernetes nodes.

While the USE method is targeted at resources, actual physical things with hard limits, it is an incomplete picture when it comes to the software running on those resources. That’s where the RED method comes in.

=== The RED Method
https://www.youtube.com/watch?v=TJLpYXbnfQ4[Tom Wilkie coined the RED method] as:

____
Rate:: The number of requests per second.
Errors:: The number of those requests that are failing.
Duration:: The amount of time those requests take.
____
On the surface the RED method seems very similar to the USE method and the Four Golden Signals. When do you apply USE vs RED?

[quote, Tom Wilkie]
____
The USE method is for resources and the RED method is for my services
____
Ahhh! Now we have frame of reference on how to apply these simplifying abstractions to the the metrics in our Kubernetes system. In coming installments some of the metrics I will be talking about describe the resources in our system. Others metrics describe the applications that use those resources.

== Optimizing Metrics in your monitoring system

=== Guidelines for choosing what to monitor

[quote, SRE handbook]
____
In choosing what to monitor, keep the following guidelines in mind:

- The rules that catch real incidents most often should be as simple, predictable, and reliable as possible.
- Data collection, aggregation, and alerting configuration that is rarely exercised (e.g., less than once a quarter for some SRE teams) should be up for removal.
- Signals that are collected, but not exposed in any prebaked dashboard nor used by any alert, are candidates for removal.
____

== Kubernetes Metrics

- https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-b190cc97f0f6[A Deep Dive into Kubernetes Metrics]


== Monitoring and Alerting

=== xref:prometheus/README.adoc[Prometheus]


=== Rules for monitoring and alerting

[quote, p64 SRE Handbook]
____
- Every time the pager goes off, I should be able to react with a sense of urgency. I can only react with a sense of urgency a few times a day before I become fatigued.
- Every page should be actionable.
- Every page response should require intelligence. If a page merely merits a robotic response, it shouldn’t be a page.
- Pages should be about a novel problem or an event that hasn’t been seen before.

____

== Questions/Open items

== Items to be demystified

- downsampling vs aggregation
