= Architecting multitenant solutions on Azure
:toc:
:icons: font
:source-highlighter: rouge
:imagesdir: ./images

== Introduction

When you build your own multitenant solution in Azure, there are several elements you need to consider that factor into your architecture.

In this series, we provide guidance about how to design, build, and operate your own multitenant solutions in Azure.

[NOTE]
====
In this series, we use the term _tenant_ to refer to *your* tenants, which might be your customers or groups of users. Our guidance is intended to help you to build your own multitenant software solutions on top of the Azure platform.

Azure Active Directory (Azure AD) also includes the concept of a tenant to refer to individual directories, and it uses the term _multitenancy_ to refer to interactions between multiple Azure AD tenants. Although the terms are the same, the concepts are not. When we need to refer to the Azure AD concept of a tenant, we disambiguate it by using the full term _Azure AD tenant_.
====

=== Scope

While Azure is itself a multitenant service, and some of our guidance is based on our experience with running large multitenant solutions, the focus of this series is on helping you build your own multitenant services, while harnessing the power of the Azure platform.

Additionally, when you design a solution, there are many areas you need to consider. The content in this section is specific to how you design for multitenancy. We don't cover all of the features of the Azure services, or all of the architectural design considerations for every application. You should read this guide in conjunction with the https://docs.microsoft.com/en-us/azure/architecture/framework/index[Microsoft Azure Well-Architected Framework] and the documentation for each Azure service that you use.

=== Intended audience

The guidance provided in this series is applicable to anyone building a multitenant application in Azure. The audience also includes independent software vendors (ISVs) and startups who are building SaaS products, whether they are targeted for businesses or consumers. It also includes anyone building a product or platform that's intended to be used by multiple customers or tenants.

The content throughout this series is designed to be useful for technical decision-makers, like chief technology officers (CTOs) and architects, and anyone designing or implementing a multitenant solution on Microsoft Azure.

[NOTE]
====
_Managed service providers_ (MSPs) manage and operate Azure environments on behalf of their customers, and work with multiple Azure Active Directory tenants in the process. This is another form of multitenancy, but it's focused on managing Azure resources across multiple Azure Active Directory tenants. This series isn't intended to provide guidance on these matters.

However, the series is likely to be helpful for ISVs who build software for MSPs, or for anyone else who builds and deploys multitenant software.
====

==== What's in this series?

The content in this series is composed of three main sections:

- xref:considerations/README.adoc[Architectural considerations for a multitenant solution]: This section provides an overview of the key requirements and considerations you need to be aware of when planning and designing a multitenant solution.
+
The pages in this section are particularly relevant for technical decision-makers, like chief technology officers (CTOs) and architects. However, anyone who works with multitenant architectures should have some familiarity with these principles and tradeoffs.

- xref:approaches/README.adoc[Architectural approaches for multitenancy]: This section describes the approaches you can consider when designing and building multitenant solutions, by using key cloud resource types. The section includes a discussion how to build multitenant solutions with compute, networking, storage, and data components, as well as deployment, configuration, governance, and cost management.
+
The architectural approaches are intended to be useful for solution architects and lead developers.

- xref:services/README.adoc[Service-specific guidance for a multitenant solution]: This section provides targeted guidance for specific Azure services. It includes discussions of the tenancy isolation models that you might consider for the components in your solution, as well as any features that are particularly relevant for a multitenant solution.
+
The service-specific guidance is useful for architects, lead developers, and anyone building or implementing Azure components for a multitenant solution.

Additionally, we provide a xref:related-services.adoc[list of related resources and links] for architects and developers of multitenant solutions.

include::considerations/README.adoc[leveloffset=+1]