= Terraform `import`
:toc:
:icons: font
:source-highlighter: rouge


[IMPORTANT]
====
Terraform import is resource specific!!! Check the _import_ section in the Terraform provider documentation for each resource type.
For example, the import instruction for Kubernetes names is described at https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace#import
====

== References
[example]
====
- https://www.terraform.io/cli/import
- https://www.terraform.io/cli/commands/import
- https://gmusumeci.medium.com/how-to-import-an-existing-azure-resource-in-terraform-6d585f93ea02
====

== Concepts

=== Current State Only
The current implementation of Terraform import can only import resources into the state. It does not generate configuration. A future version of Terraform will also generate configuration.

Because of this, prior to running terraform import it is necessary to write manually a resource configuration block for the resource, to which the imported object will be mapped.

While this may seem tedious, it still gives Terraform users an avenue for importing existing resources.


=== ID

#ID is dependent on the resource type being imported.# For example, for AWS instances it is the instance ID (i-abcd1234) but for AWS Route53 zones it is the zone ID (Z12ABC4UGMOZ2N). Please reference the provider documentation for details on the ID format. If you're unsure, feel free to just try an ID. If the ID is invalid, you'll just receive an error message.

=== Preparation
To import a resource, first write a resource block for it in your configuration, establishing the name by which it will be known to Terraform:
[source]
----
resource "aws_instance" "example" {
  # ...instance configuration...
}
----



== Cheatsheet

[cols="10,20m,20,60m"]
|===
|Provider|Resource Type|ID Pattern|Command Example

|kubernetes
|kubernetes_namespace
|https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace#import[namespace]
|$ terraform import kubernetes_namespace.n terraform-example-namespace

|helm
|helm_release
|https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#import[`namespace/name`]
|$ terraform import helm_release.csi_driver_blob kube-system/blob-csi-driver


|===