= Strategy Frameworks
:toc:
:imagesdir: ./images

.Readings/Refernces
====
- https://www.cascade.app/blog/best-strategy-frameworks[The 5 Best Strategic Frameworks for your Organization]
- https://www.cascade.app/blog/guide-to-strategy-implementation[Strategy Implementation: The 6 Step Process]
- https://www.cascade.app/blog/strategic-analysis?hsLang=en-us[What is Strategic Analysis? 8 Best Strategic Analysis Tools + Examples]
====

== What is a strategic framework?

A strategic framework **is a tool that will assist you at a specific stage of the strategic management cycle, most commonly during the strategy formulation and evaluation stage.**

Usually, strategic frameworks will require you to categorize your goals into a series of groupings. Choosing a strategy framework to follow keeps you focused on your goals. It inserts clarity in your strategic processes and enables you to navigate reality’s mess.

There are 3 key steps in _implementing a strategy_ framework. We’ll go through each of these steps.

== How to implement the right strategic framework

=== Step 1: Choose the right strategic framework

IMPORTANT: A key part of choosing the right framework is self-reflection.

Where does your organization stand? What are you trying to achieve? What are your main strengths and weaknesses? All these questions play heavily into your selection of the best strategy framework.

For each of 5 the strategy frameworks below, we have outlined why they're useful. We've also provided examples of what types of organizations might use them.

_Recommended reading_: https://www.cascade.app/blog/strategic-analysis?hsLang=en-us[What is Strategic Analysis? 8 Best Strategic Analysis Tools + Examples]
