= Uptime
:toc: auto
:stem: latexmath

== Readings/Materials

====
- https://en.wikipedia.org/wiki/Uptime
- https://www.logicmonitor.com/blog/uptime-vs-availability
- https://www.manageengine.com/network-monitoring/faq/calculate-device-availability-uptime.html
- https://blog.paessler.com/why-uptime-does-not-mean-availability
====

== What is uptime?

[quote, wikipedia]
____
Uptime is a measure of system reliability, expressed as the percentage of time a machine, typically a computer, has been working and available.
____


Uptime refers to the percentage of time a system is ready for operation under normal circumstances. This metric measures system, solution, or infrastructure reliability and most commonly refers to a computer.

So, *uptime is how long a machine has been working and available, expressed as a percentage of time*. However, uptime does not necessarily mean all services and applications are available and ready for use. 

When looking at a service-level agreement (SLA), guaranteed uptime is determined by past performance. However, it is not an indicator of what will happen in the future. 

So yes, uptime can be an indicator of availability, but it is by no means a guarantee. 

== How to calculate?

[stem]
++++
Uptime = 24 * 60 * 60 - sum downtime

Availability = 1 - (sum downtime) / 86400 * 100
++++


=== Health Check based uptime

The uptime can be calculated as below for a health check endpoint which is polled every 30 seconds:

==== Per day uptime

The uptime will be following if health check fails for 3 times in a *24* hour time box.

====
Uptime = 24 * 60 * 60 - 3 * 30 = 86400 - 90 = 86310
====

=== Per day availability

Then the availability will be caclulated as

====
Availability = 86310 / 86400 * 100 = 99.8958%
====