= RBAC Authorization
:toc:

.References
[sidebar]
****
* https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Using RBAC Authorization]
* https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings[Default roles and role bindings]
****

== Cheatsheet

[CAUTION]
====
Take care when modifying ClusterRoles and ClusterRoleBindings with names that have a `system:` prefix. Modifications to these resources can result in non-functional clusters.
====

=== Get system default ClusterRoles

[source,bash]
----
s0001321@mC02FG16BML85 ~ % kubectl get clusterroles -l kubernetes.io/bootstrapping=rbac-defaults

----

== Excerpts

=== Referring to subjects

A RoleBinding or ClusterRoleBinding binds a role to subjects. Subjects can be groups, users or ServiceAccounts.

Kubernetes represents usernames as strings. These can be: plain names, such as "alice"; email-style names, like "bob@example.com"; or numeric user IDs represented as a string. It is up to you as a cluster administrator to configure the authentication modules so that authentication produces usernames in the format you want.

.Caution
[CAUTION]
====
The prefix `system:` is reserved for Kubernetes system use, so you should ensure that you don't have users or groups with names that start with `system:` by accident. Other than this special prefix, the RBAC authorization system does not require any format for usernames.
====

In Kubernetes, Authenticator modules provide group information. Groups, like users, are represented as strings, and that string has no format requirements, other than that the prefix `system:` is reserved.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/[ServiceAccounts] have names prefixed with `system:serviceaccount:`, and belong to groups that have names prefixed with `system:serviceaccounts:`.

.Note
[NOTE]
====
* `system:serviceaccount`: (singular) is the prefix for service account usernames.
* `system:serviceaccounts`: (plural) is the prefix for service account groups.
====