= Helm template development
:toc:

== Externalize container `args` property through helm values
To externalize the container `args` attribute, define a value in `values.yaml` as a placeholder. The actual values of this placeholder variable can be specified through helm command line flags `--set`. Some special technique will be used to specify an array value through `--set` command line flag.

By default, there will be no actual values for the `args` property in the container definition. Hence, the `args` section should not appear in generated kubernetes manifest file if there are no actual values.

The `args` section should list the actual values specified through helm chart values either in values file or command line flags(`--set`,`--set-string`, etc)

=== values files
In the example below, `application.arg` will be the placeholder value for the container args.

[source, yaml]
----
## active profile for the application
application:
  activeProfiles: "dev"
  projectedBootstrapPath: /etc/config/bootstrap/
  projectedCredentialsPath: /etc/config/credentials/
  args: []
----

=== Kubernetes deployment template
The snippet below defines that the `args` section will get generated only if values are provided for variable `application.args`. Then it iterates all the values as a YAML list.

[source, yaml]
----
          {{- if .Values.application.args }}
          args:
            {{- range .Values.application.args }}
            - {{ .  }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: config-credentials
              mountPath: {{ .Values.application.projectedCredentialsPath | trimSuffix "/" }}
              readOnly: true
            - name: cache-volume
              mountPath: {{ .Values.observability.appInsights.agentPath }}
            - name: config-application-insights
              mountPath: {{ .Values.observability.appInsights.configPath }}
            - name: config-bootstrap
              mountPath: {{ .Values.application.projectedBootstrapPath | trimSuffix "/" }}
              readOnly: true
----

=== Specify custom values for `application.args` in command line with `--set` flag
The way to specify an array value for a values key is follow the pattern of `--set "application.args={a,b,c}"`.

NOTE: This technique only works with helm 3.0+.

The example below is a helm template debug command line that uses this technique
[source, bash]
----
helm template tt1 ./my-template --debug --set "application.args={--debug.config.properties=spring.cloud.azure.credential.client-secret\,spring.cloud.azure.eventhubs.processor.checkpoint-store.account-key,--spring.profiles.active=dev,--debug}" > helm-debug.yaml
----

Output

[source,yaml]
----
          args:
            - --debug.config.properties=spring.cloud.azure.credential.client-secret,spring.cloud.azure.eventhubs.processor.checkpoint-store.account-key
            - --spring.profiles.active=dev
            - --debug
          volumeMounts:
            - name: config-credentials
              mountPath: /etc/config/credentials
              readOnly: true
            - name: cache-volume
              mountPath: /data/observability/agent
            - name: config-application-insights
              mountPath: /data/observability/config
            - name: config-bootstrap
              mountPath: /etc/config/bootstrap
              readOnly: true
----
