= Linux Control Groups v2 (cgroups v2)
:toc: auto

.References
[sidebar]
****
* https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html
* https://man7.org/linux/man-pages/man7/cgroups.7.html#CGROUPS_VERSION_2[cgroups(7) — Linux manual page]

****

== Introduction
=== Terminology
“cgroup” stands for “control group” and is never capitalized. The singular form is used to designate the whole feature and also as a qualifier as in “cgroup controllers”. When explicitly referring to multiple individual control groups, the plural form “cgroups” is used.

=== What is cgroup?

[quote, cgroups man page]
====

Control groups, usually referred to as cgroups, are a Linux
kernel feature which allow processes to be organized into
hierarchical groups whose usage of various types of resources can
then be limited and monitored.  The kernel's cgroup interface is
provided through a pseudo-filesystem called cgroupfs.  Grouping
is implemented in the core cgroup kernel code, while resource
tracking and limits are implemented in a set of per-resource-type
subsystems (memory, CPU, and so on).

====


cgroup is a mechanism to organize processes hierarchically and distribute system resources along the hierarchy in a controlled and configurable manner.

cgroup is largely composed of two parts - the core and controllers. cgroup core is primarily responsible for hierarchically organizing processes. A cgroup controller is usually responsible for distributing a specific type of system resource along the hierarchy although there are utility controllers which serve purposes other than resource distribution.

cgroups form a tree structure and every process in the system belongs to one and only one cgroup. All threads of a process belong to the same cgroup. On creation, all processes are put in the cgroup that the parent process belongs to at the time. A process can be migrated to another cgroup. Migration of a process doesn’t affect already existing descendant processes.

Following certain structural constraints, controllers may be enabled or disabled selectively on a cgroup. All controller behaviors are hierarchical - if a controller is enabled on a cgroup, it affects all processes which belong to the cgroups consisting the inclusive sub-hierarchy of the cgroup. When a controller is enabled on a nested cgroup, it always restricts the resource distribution further. The restrictions set closer to the root in the hierarchy can not be overridden from further away.



== Creating cgroups and moving processes

A cgroup filesystem initially contains a single root cgroup, '/',
which all processes belong to.  A new cgroup is created by
creating a directory in the cgroup filesystem:

    mkdir /sys/fs/cgroup/cpu/cg1

This creates a new empty cgroup.

A process may be moved to this cgroup by writing its PID into the
cgroup's cgroup.procs file:

    echo $$ > /sys/fs/cgroup/cpu/cg1/cgroup.procs

Only one PID at a time should be written to this file.

Writing the value 0 to a cgroup.procs file causes the writing
process to be moved to the corresponding cgroup.

When writing a PID into the cgroup.procs, all threads in the
process are moved into the new cgroup at once.

Within a hierarchy, a process can be a member of exactly one
cgroup.  Writing a process's PID to a cgroup.procs file
automatically removes it from the cgroup of which it was
previously a member.

The cgroup.procs file can be read to obtain a list of the
processes that are members of a cgroup.  The returned list of
PIDs is not guaranteed to be in order.  Nor is it guaranteed to
be free of duplicates.  (For example, a PID may be recycled while
reading from the list.)

In cgroups v1, an individual thread can be moved to another
cgroup by writing its thread ID (i.e., the kernel thread ID
returned by clone(2) and gettid(2)) to the tasks file in a cgroup
directory.  This file can be read to discover the set of threads
that are members of the cgroup.
