= SOLID Principles
:toc:
:icons: font


- SRP - Single Responsibility Principle
- OCP - Open/Close Principle
- LSP  - Liskov Substitution Principle
- ISP   - Interface Segregation Principle
- DIP  -  Dependency Inversion Principle

== References
- https://stackify.com/solid-design-principles/
- https://stackify.com/solid-design-open-closed-principle/
- https://stackify.com/solid-design-liskov-substitution-principle/
- https://stackify.com/interface-segregation-principle/
- https://stackify.com/dependency-inversion-principle/
- https://medium.com/mindorks/solid-principles-explained-with-examples-79d1ce114ace

== SRP

== OCP

=== Definition of the Open/Closed Principle
Robert C. Martin considered this principle as the “the most important principle of object-oriented design”. But he wasn’t the first one who defined it. Bertrand Meyer wrote about it in 1988 in his book Object-Oriented Software Construction. He explained the Open/Closed Principle as:
[quote, Bertrand Meyer]
____
Software entities (classes, modules, functions, etc.) should be open for extension, but closed for modification.
____

The general idea of this principle is great. It tells you to write your code so that you will be able to add new functionality without changing the existing code. That prevents situations in which a change to one of your classes also requires you to adapt all depending classes. Unfortunately, Bertrand Mayer proposes to use inheritance to achieve this goal:
[quote, Bertrand Mayer]
____
A class is closed, since it may be compiled, stored in a library, baselined, and used by client classes. But it is also open, since any new class may use it as parent, adding new features. When a descendant class is defined, there is no need to change the original or to disturb its clients.
____

But as we’ve learned over the years and as other authors explained in great details, e.g., Robert C. Martin in his articles about the SOLID principles or Joshua Bloch in his book Effective Java, #inheritance introduces tight coupling if the subclasses depend on implementation details of their parent class#.
That’s why Robert C. Martin and others redefined the Open/Closed Principle to the Polymorphic Open/Closed Principle. It uses interfaces instead of superclasses to allow different implementations which you can easily substitute without changing the code that uses them. The interfaces are closed for modifications, and you can provide new implementations to extend the functionality of your software.
The main benefit of this approach is that an interface introduces an additional level of abstraction which enables loose coupling. The implementations of an interface are independent of each other and don’t need to share any code. If you consider it beneficial that two implementations of an interface share some code, you can either use inheritance or composition.

=== Key Points
- Advocates interfaces over superclasses -- #inheritance introduces tight coupling if the subclasses depend on implementation details of their parent class#

== LSP
The principle defines that objects of a superclass shall be replaceable with objects of its subclasses without breaking the application. That requires the objects of your subclasses to behave in the same way as the objects of your superclass. You can achieve that by following a few rules, which are pretty similar to the design by contract concept defined by Bertrand Meyer.



== ISP
=== Goal
Similar to the Single Responsibility Principle, the goal of the Interface Segregation Principle is to #reduce the side effects and frequency of required changes# by splitting the software into multiple, independent parts.

== DIP
=== Definition of the Dependency Inversion Principle
The general idea of this principle is as simple as it is important: High-level modules, which provide complex logic, should be easily reusable and unaffected by changes in low-level modules, which provide utility features. To achieve that, you need to introduce an abstraction that decouples the high-level and low-level modules from each other.

Based on this idea, Robert C. Martin’s definition of the Dependency Inversion Principle consists of two parts:

. High-level modules should not depend on low-level modules. Both should depend on abstractions.
. Abstractions should not depend on details. Details should depend on abstractions.

An important detail of this definition is, that high-level *and* low-level modules depend on the abstraction. The design principle does not just change the direction of the dependency, as you might have expected when you read its name for the first time. It splits the dependency between the high-level and low-level modules by introducing an abstraction between them. So in the end, you get two dependencies:

. the high-level module depends on the abstraction, and
. the low-level depends on the same abstraction.