= Product As a Product
:toc:
:icons: font
:imagesdir: ./images


.icon:book[role=yeti] Resources
****
- https://tomgeraghty.co.uk/index.php/platform-as-a-product/[Platform as a Product]
- https://tomgeraghty.co.uk/index.php/platform-vs-product/[Platform Engineering and the Platform Operating Model]
- https://martinfowler.com/articles/talk-about-platforms.html[What I Talk About When I Talk About Platforms]
- https://thenewstack.io/platform-as-a-product-true-devops/[Platform as a Product: True DevOps?]
- https://www.youtube.com/watch?v=O3vvo2Sinww[#ProductCon: Platform Product Management: Changing What’s Possible by The New York Times SVP of Prod]
- https://www.youtube.com/watch?v=bPIpteB-qtk[How to Understand the Product Platform by American Express Sr PM]
- https://www.youtube.com/watch?v=b8YHCDMxqfg[https://www.youtube.com/watch?v=b8YHCDMxqfg]
- https://www.youtube.com/watch?v=PDBapcenckk[Webinar: Building Platform Products by LinkedIn Product Lead, Seema Jethani]

****

== What is a Platform?

[Quote, From Evan Bottcher, 2018]
____
A digital platform is a foundation of self-service APIs, tools, services, knowledge and support which are arranged as a compelling internal product. Autonomous delivery teams can make use of the platform to deliver product features at a higher pace, with reduced co-ordination.
____

From https://martinfowler.com/articles/talk-about-platforms.html[What I Talk About When I Talk About Platforms] by Martin Fowler

[Quote, Martin Fowler]
____
A digital platform is a foundation of self-service APIs, tools, services, knowledge and support which are arranged as a compelling internal product. Autonomous delivery teams can make use of the platform to deliver product features at a higher pace, with reduced co-ordination.
____

=== Characteristics of platforms

*A platform should:*

Reduce Developer Cognitive Load:: – software developers can be overloaded with system complexity, tooling, documentation, and organisational noise. The PaaP approach intends to reduce that cognitive load so that developers can focus on solving the problem and providing business value, quickly.

Reduce Operational Burden:: – this includes everything from reducing utilisation of people, reducing friction and handoffs, improving observability, to capacity management, and documentation. Basically – making everyone’s jobs easier alongside maximising the technology ROI for the business.

Optimise for Fast Flow:: – most, maybe all, organisations want to reduce the time it takes for an idea to begin returning value. This is true of commercial businesses, public sector, and other organisations such as charities.  This involves optimising the technology for flow (automation, CI/CD tooling etc) as well as people, processes and practices. This is why we can’t separate the People from the Platform: the PaaP approach is not solely technological.




== Why and how to build Internal Developer Platform

In his latest Gartner report, https://www.gartner.com/analyst/55907/Manjunath-Bhat[Manjunath Bhat], focuses on three key pillars around https://humanitec.com/blog/gartner-internal-developer-platforms-platform-engineering[why and how to build your IDP]:

. Improve developer experience by building internal developer platforms to reduce cognitive load, developer toil and repetitive manual work.
. Platforms don’t enforce a specific toolset or approach. It is about making it easy for developers to build and deliver software while not abstracting away useful and differentiated capabilities of the underlying core services.
. Platform engineering teams treat platforms as a product (used by developers) and design the platform to be consumed in a self-service manner.

== Platform As A Product
I would strongly advise also looking at internalising https://servicedesigntools.org/[service design capabilities] and expertise to help teams design and build the platform. The platform as a product approach is fundamentally a practice to enable improved efficiency, improved product quality and reliability and faster speed to market, via reducing cognitive load for developers, faster flow of work, reduced handoffs, and enabling developers to focus on delivering value.



=== Insights from Martin Fowler (https://martinfowler.com/articles/talk-about-platforms.html[What I Talk About When I Talk About Platforms])

It is a real struggle to find the right balance between autonomous diversification and mandated consolidation, and that is even more difficult to predict up front. A key ingredient for success in finding this balance is that platforms must be compelling to use, they cannot stand on a mandate alone. Your existing shared infrastructure function has a monopoly and delivery teams have no viable alternative. A little competition is a necessary ingredient to drive the product thinking ensuring that every platform feature adds value instead of creating constraints and coupling.

[sidebar]
****
A key ingredient for success in finding this balance is that platforms must be compelling to use
****

What makes a platform compelling? Here are a few ideas:

- The platform is self-service for the overwhelming majority of use cases.
- The platform is composable, containing discrete services that can be used independently.
- The platform does not force an inflexible way of working upon the delivery team.
- The platform is quick and cheap to start using, with an easy on-ramp (e.g. Quick start guides, documentation, code samples)
- The platform has a rich internal user community for sharing
- The platform is secure and compliant by default
- The platform is up to date

Ultimately the delivery infrastructure platform is compelling when it is easier to consume the platform capability than building and maintaining your own thing. Netflix describes their centralised tooling as ‘the paved road’ - teams do not have to make use of the tooling but are responsible for all the costs of maintaining their own alternatives.

A platform should also be more than just software and APIs - it is documentation, and consulting, and support and evangelism, and templates and guidelines.

