= Proclaiming Your Dream: Developing Vision and Mission Statements
:toc:
:imagesdir: ./images

== Main Section
Creating your organization's vision and mission statements are the first two steps in the VMOSA action planning process. Developing a vision and mission statement is crucial to the success of community initiatives. These statements explain your group's aspirations in a concise manner, help your organization focus on what is really important, and provide a basis for developing other aspects of your strategic plan. This section provides a guide for developing and implementing your organization's vision and mission statements.

=== What is a vision statement?
Your vision is your dream. It's what your organization believes are the ideal conditions for your community; that is, how things would look if the issue important to you were completely, perfectly addressed. It might be a world without war, or a community in which all people are treated as equals, regardless of gender or racial background.

Whatever your organization's dream is, it may be well articulated by one or more vision statements, which are short phrases or sentences that convey your community's hopes for the future. By developing a vision statement or statements, your organization clarifies the beliefs and governing principles of your organization, first for yourselves, and then for the greater community.

There are certain characteristics that most vision statements have in common. In general, vision statements should be:

- Understood and shared by members of the community
- Broad enough to include a diverse variety of local perspectives
- Inspiring and uplifting to everyone involved in your effort
- Easy to communicate - for example, they are generally short enough to fit on a T-shirt

Here are some examples of vision statements that meet the above criteria:

- A community where all individuals and families achieve their human potential.
- CALCASA envisions a world free from sexual violence.
- A future where tobacco is a thing of the past. (Truth Initiative)
- A world without Alzheimer’s Disease. (Alzheimer’s Association)
- The United States is a humane community in which all animals are treated with respect and kindness. (ASPCA)
- A world where everyone has a decent place to live. (Habitat for Humanity)

=== What is a mission statement?

The next step of the action planning process is to ground your vision in practical terms. This is where developing a mission statement comes in. An organization's mission statement describes what the group is going to do and why it's going to do that. An example is "Promoting care and caring at the end of life through coalitions and advocacy."

Mission statements are similar to vision statements, in that they, too, look at the big picture. However, they're more concrete, and they are definitely more "action-oriented" than vision statements. Your vision statement should inspire people to dream; your mission statement should inspire them to action.

The mission statement might refer to a problem, such as an inadequate housing, or a goal, such as providing universal access to health care. And, while they don't go into a lot of detail, they hint - very broadly - at how your organization might fix these problems or reach these goals. Some general guiding principles about mission statements are that they are:

- _Concise_. While not as short as vision statements, mission statements generally still get their point across in one sentence.
- _Outcome-oriented_. Mission statements explain the fundamental outcomes your organization is working to achieve.
- _Inclusive_. While mission statements do make statements about your group's key goals, it's very important that they do so very broadly. Good mission statements are not limiting in the strategies or sectors of the community that may become involved in the project.

The following examples should help you understand what we mean by effective mission statements.

- Promoting community health and development by connecting people, ideas and resources. (Community Tool Box)
- The California Coalition Against Sexual Assault (CALCASA) provides leadership, vision and resources to rape crisis centers, individuals and other entities committed to ending sexual violence.
- Our mission is to eliminate Alzheimer's disease through the advancement of research; to provide and enhance care and support for all affected; and to reduce the risk of dementia through the promotion of brain health. (Alzheimer’s Association)
- The mission of the ASPCA, as stated by Henry Bergh in 1866, is "to provide effective means for the prevention of cruelty to animals throughout the United States”.
- Seeking to put God’s love into action, Habitat for Humanity brings people together to build homes, communities and hope.

=== Why should you create vision and mission statements?

Why is it important that your organization develops vision and mission statements like those above? First of all, these statements can help your organization focus on what is really important. Although your organization knows what you are trying to do to improve your community, it's easy to lose sight of this when dealing with day-to-day organizational hassles. Your vision and mission statements remind members what is important.

Second, your vision and mission statements give other individuals and organizations a snapshot view of what your group is and what it wants to accomplish. When your vision and mission statements are easily visible (for example, if they are on the letterhead of your stationary), people learn about your organization without having to work hard for the information. Then, those with common interests can take the time necessary to learn more. This efficiency is very helpful when you are recruiting other people and organizations to join your effort.

Finally, vision and mission statements focus members on their common purpose . Not only do the statements themselves serve as a constant reminder of what is important to your organization, the process of developing them allows people to see the organization as "theirs”. Creating these statements builds motivation as members will believe in something more completely if they had a hand in developing it.

Having a clear and compelling vision statement has other advantages, such as:

- Drawing people to common work
- Giving hope for a better future
- Inspiring community members to realize their dreams through positive, effective action
- Providing a basis for developing the other aspects of your action planning process: your mission, objectives, strategies, and action plans

Having a clear and compelling mission statement also has more advantages, such as:

- Converting the broad dreams of your vision into more specific, action-oriented terms
- Explaining your goals to interested parties in a clear and concise manner
- Enhancing your organization's image as being competent and professional, thus reassuring funding sources that their investment was (or would be!) a smart choice

=== How do you create vision and mission statements?

Now having a better understanding of vision and mission statements, your organization has the tools to develop your unique statements. If your group has already developed vision and mission statements, you might wish to look at them in light of the criteria we discussed above. If members of your organization feel your current statements could be improved, this process can be easily used to modify them. Let’s begin.

==== Learn what is important to people in your community

As developing your vision and mission statements is the first step in creating your action plan, it is especially important that these first steps are well grounded in community beliefs and values. Awareness of the important issues in your community is critical for the development of a strong, effective, and enduring action group.

Therefore, one of the first steps you should take when developing the vision and mission of your organization is to define the issue(s) that matter most to people in your community. How do you go about doing so?

There are many different ways you can gather this information, including:

===== Conducting "public forums" or "listening sessions" with members of the community to gather ideas, thoughts, and opinions about how they would like to see the community transformed.

In public forums or listening sessions, people gather from throughout the community to talk about what is important to them. These meetings are usually led by facilitators, who guide a discussion of what people perceive to be the community's strengths and problems, and what people wish the community was like. Someone typically records these meetings, and a transcript of what is said provides a basis for subsequent planning.

===== Holding focus groups with the people interested in addressing the issue(s), including community leaders, people most affected by the issues, businesses, church leaders, teachers, etc.

Focus groups are similar to public forums and listening sessions, but they are smaller and more intimate. Generally speaking, they are comprised of small groups of people with similar backgrounds, so they will feel comfortable talking openly about what concerns them. For example, the group members are generally about the same age, are of the same ethnic group, or have another common identity and/or experience. Focus groups function like public forums, and also use facilitators and recorders to focus and document discussion.

Your organization may hold focus groups with several different groups of people to get the most holistic view of the issue at hand. For example, if your organization is involved in child health, you might have one focus group with health care providers, another with parents or children, and still another with teachers. Once you have a rough mission statement, you might again hold a focus group for feedback.

===== Obtaining interviews with people in leadership and service positions, including such individuals as local politicians, school administrators, hospital and social service agency staff, about what problems or needs they believe exist in your community.

Often, these individuals will have both facts and experiences to back up their perspectives. If so, this data can be used later if and when you apply for funding, or when you request community support to address the issues. More information on this topic can be found in Chapter 3, Section 12: Conducting Interviews.

It’s important to realize that these different ways of gathering information from your community are not mutually exclusive. In fact, if you have the resources, it is recommended to do all of the above: to have some time for the community at large to respond, then spend more time in focus groups with the people you believe might contribute greatly to (or be most affected by) some of the issues brought up in the public forum. And finally, some one-on-one time with community leaders can strengthen your knowledge and purpose; remember, there are community members who have been wrestling with the same issues you are now looking at for a long time. Take advantage of that experience so you don’t waste time on something that’s already been done.

==== Decide what to ask

No matter if you are talking to one person or a crowd, your purpose is the same: to learn what matters in your community. Here's a list of questions you might use to focus your discussions with community members. These questions may be used for individual interviews, focus groups, public forums, or in any other way you choose to gather information.

- What is your dream/vision for our community?
- What would you like to see change?
- What kind of community (or program, policy, school, neighborhood, etc.) do we want to create?
- What do you see as the community's (or school's, neighborhood's, etc.) major issues or problems?
- What do you see as the community's major strengths and assets?
- What do you think should be the purpose of this organization (or effort)?
- Why should these issues be addressed?
- What would success look like?

When your organization is gathering input, the facilitator should encourage everyone to share their most idealistic, hopeful, and positive ideas. Don't worry right now about what's practical and what's not - this can be narrowed down later. Encourage everyone to be bold and participate, and to remember that you are trying to articulate a vision of a better community.

==== Decide on the general focus of your organization

Once members of your organization have heard what the community has to say, it's time to decide the general focus of your organization or initiative. First of all, what topic is most important to your organization and your community? For example, will you tackle urban development or public health issues? Racism or economic opportunity?

A second question to answer is at what level will your organization work. Will your organization begin only in one school, or in one neighborhood, or in your city? Or will your initiative's focus be broader, working on a state, national, or even international level?

These are questions for which there are no easy answers. Your organization will need to consider lessons learned from the community and decide through thoughtful discussion the best direction for your organization. We suggest you open this discussion up to everyone in your organization to obtain the best results.

However, if your organization is receiving grant money or major funding from a particular agency, the grant maker may specify what the general goal of your group should be. For example, if your group accepts a grant to reduce child hunger, at least part of its mission will be devoted to this purpose. Even in these circumstances, however, the community should determine the ultimate vision and mission that will best advance what matters to local people.

==== Develop your vision and mission statements

Now that your organization has a clearer understanding of what the group will do and why, you are in a prime position to develop the statements that will capture your ideas.

As you are looking at potential statements, remember to keep them broad and enduring. Vision and mission statements wide in scope allow for a sense of continuity with a community's history, traditions, and broad purposes. Additionally, vision and mission statements that are built to last will guide efforts both today and tomorrow.

===== Vision Statements

First of all, remind members of your organization that it often takes several vision statements to fully capture the dreams of those involved in a community improvement effort. You don't need - or even want - just one "perfect" phrase. Encourage people to suggest all of their ideas and write them down, possibly on poster paper at the front of the room, so people can be further inspired by the ideas of others. As you do this, remind the group of:

- What you have learned from your discussions with community members
- What your organization has decided will be your focus
- What you learned about vision statements at the beginning of this section

If you have a hard time getting started, you might wish to check out some of the vision statements in this section's Examples. You might ask yourself how well they meet the above suggestions.

After you have brainstormed a list of suggestions, your group can discuss critically the different ideas. Oftentimes, some of the vision statements will jump out at you - someone will suggest it, and people will just instantly think, "That's it!"

If it’s more complicated than that, you should ask yourselves the following questions:

- Will it draw people to common work?
- Does it give hope for a better future?
- Will it inspire community members to realize their dreams through positive, effective action?
- Does it provide a basis for developing the other aspects of your action planning process?

A final caution: try not to get caught up in having a certain number of vision statements for your organization. Whether you ultimately end up with two vision statements or ten, what is most important is that the statements together provide a holistic view of your organization’s vision.

===== Mission Statements

The process of writing your mission statement is similar to developing your vision statements. The same brainstorming process can help you develop possibilities for your mission statement. Remember, though, that unlike vision statements, you will want to develop a single mission statement for your work. After brainstorming possible statements, you will want to answer questions for each one:

- Does it describe what your organization will do and why it will do it?
- Is it concise (one sentence)?
- Is it outcome oriented?
- Is it inclusive of the goals and people who may become involved in the organization?

Together, your organization can decide on a statement that best meets these criteria.

==== Obtain consensus on your vision and mission statements

Once members of your organization have developed your vision and mission statements, your next step might be to learn what other community members think of them before you use the statements regularly.

To do this, you could talk to the same community leaders or focus group members you spoke to originally. First of all, this can help you ensure that they don't find the statements offensive in any way. For example, an initiative that wants to include young men more fully in its teen pregnancy prevention project might have "Young men in Asheville are the best informed" as one of their vision statements. But taken out of context, some people community members might believe this statement means young men are given better information or education than young women, thus offending another group of people.

Second, you will want to ensure that community members agree that the statements together capture the spirit of what they believe and desire. Your organization might find it has omitted something very important by mistake.

==== Decide how you will use your vision and mission statements

Finally, it's important to remember that while developing the statements is a huge step for your organization worth celebration, there is more work to be done. Next, you have to decide how to use these statements. Otherwise, all of your hard work would lead to nothing. The point is to get the message across.

There are many ways in which your organization may choose to spread its vision and mission statements. To name just a few examples, you might:

- Add them to your letterhead or stationary
- Use them on your website
- Give away T-shirts, or bookmarks, or other small gifts with them
- Add them to your press kit
- Use them when you give interviews
- Display them on the cover of your annual report

...and so on. Again, this is a step that will use all of your creativity.

== Checklist


___You have shared your understanding of vision and mission statements with members of your organization

___You understand what is important to people in your community

___You have decided on the general focus (topic and scope) of your organization

___You have developed your vision and mission statements

___You have obtained consensus on your vision and mission statements

___You have decided how to use your vision and mission statements

