= Creating Objectives
:toc:

 Learn how to develop SMART+C objectives (Specific, Measurable, Achievable, Relevant, Timed, and Challenging) for your efforts.

== Main Section

To obtain results, we need to articulate the outcomes we desire.

This section focuses on developing specific objectives that will help make your vision and mission a reality.

=== What are objectives?

Objectives are the specific measurable results of the initiative. Objectives specify how much of what will be accomplished by when. For example, one of several objectives for a community initiative to promote care and caring for older adults might be: "By 2024 (by when), to increase by 20% (how much) those elders reporting that they are in daily contact with someone who cares about them (of what)."

*There are three basic types of objectives*. They are:

- _Process objectives_. These are the objectives that provide the groundwork or implementation necessary to achieve your other objectives. For example, the group might adopt a comprehensive plan for improving neighborhood housing. In this case, adoption of the plan itself is the objective.
- _Behavioral objectives_. These objectives look at changing the behaviors of people (what they are doing and saying) and the products (or results) of their behaviors. For example, a neighborhood improvement group might develop an objective for having an increased amount of home repair taking place (the behavior) and fewer houses with broken or boarded-up windows (the result).
- _Community-level outcome objectives_. These are often the product or result of behavior change in many people. They are focused on change at the community level instead of an individual level. For example, the same neighborhood group might have an objective of increasing the percentage of people living in the community with adequate housing as a community-level outcome objective.

It's important to understand that these different types of objectives aren't mutually exclusive. Most groups will develop objectives in all three categories.

Objectives should be *S.M.A.R.T. + C*.:

- _Specific_. That is, they tell how much (e.g., 10%) of what is to be achieved (e.g., what behavior of whom or what outcome) by when (e.g., by 2025)?
- _Measurable_. Information concerning the objective can be collected, detected, or obtained.
- _Achievable_. It is feasible to pull them off.
- _Relevant to the mission_. Your organization has a clear understanding of how these objectives fit in with the overall vision and mission of the group.
- _Timed_. Your organization has developed a timeline (a portion of which is made clear in the objectives) by which they will be achieved.
- _Challenging_. They stretch the group to set its aims on significant improvements that are important to members of the community.

=== Why should you create objectives?

There are many good reasons to develop objectives for your initiative. They include:

- Having benchmarks to show progress.
- Completed objectives can serve as a marker to show members of your organization, funders, and the greater community what your initiative has accomplished.
- Creating objectives helps your organization keep focused on initiatives most likely to have an impact.
- Keeping members of the organization working toward the same long-term goals

=== When should you create objectives?
Your community organization should create objectives when:

- Your organization has developed (or revamped) its vision and mission statements, and is ready to take the next step in the planning process.
- Your organization's focus has changed or expanded. For example, perhaps your organization's mission relates to care and caring at the end of life. You have recently been made aware of new resources, however, to positively affect the lives of those deeply affected by the death of a loved one. If your organization were to apply for this new grant, it would clearly expand upon your current work, and would require objectives as you developed your action plan.
- The organization wants to address a community issue or problem, create a service, or make a community change that requires:
* Several years to complete. For example, your child health organization might hope to increase the percentage of students who finish high school - a task that may take several years to complete.
* A change in behavior of large numbers of people. For example, your organization may be trying to reduce risks for cardiovascular diseases, and one of your objectives may be to increase the number of adults who engage in physical activity in your community.
* A multi-faceted approach. For example, with a problem as complex as substance abuse, your organization may have to worry about tackling related issues, such as access to drugs, available drug rehabilitation services, legal consequences for drug use, etc., as well as reducing the prevalence (how often or how much) of drug use.

=== How do you create objectives?
So once your organization has decided that it does wish to develop objectives, how do you go about doing so? Let's look at the process that will help you to define and refine objectives for your organization.

==== Define or reaffirm your vision and mission statements

The first thing you will need to do is review the vision and mission statements your organization has developed. Before you determine your objectives, you should have a "big picture" that they fit into.

==== Determine the changes to be made

The crux of writing realistic objectives is learning what changes need to happen in order to fulfill your mission.

There are many ways to do this, including:

- _Research what experts in your field believe to be the best ways to solve the problem_. For many community issues, researchers have developed useful ideas of what needs to occur to see real progress. This information may be available through local libraries, the Internet, state and national agencies, national nonprofit groups, and university research groups.
- _Discuss with local experts what needs to occur_. Some of the people with whom you may wish to talk include:
* Other members of your organization
* Local experts, such as members of other, similar organizations who have a great deal of experience with the issue you are trying to change
* Agents of change, or the people in a position to contribute to the solution. Agents of change might include teachers, business leaders, church leaders, local politicians, community members, and members of the media.
* Targets of change, the people who experience the problem or issue on a day-to-day basis and those people whose actions contribute to the problem. Changing their behavior will become the heart of your objectives.
- _Discuss the logistical requirements of your own organization to successfully address community needs_. At the same time your organization is looking at what needs to happen in the community to solve the issue important to you, you should also consider what your organization requires to get that done. Do you need an action plan? Additional funding? More staff, or more training for additional staff? This information is necessary to develop the process objectives we talked about earlier in this section.

At this point in the planning process, you don't need hard and fast answers to the above questions. What you should develop as part of this step is a general list of what needs to occur to make the changes you want to see.

====
*For example, perhaps your group has decided upon the following mission: "To reduce risk for cardiovascular diseases through a community-wide initiative."* At this point in your research (without getting into specifics), your organization might have decided that your objectives will be based on the following general goals:

- Begin smoking cessation programs
- Begin smoking prevention programs
- Bring about an increase in aerobic exercise
- Decrease the amount of obesity
- Encourage healthier diets
- Increase preventative medicine (for example, more checkups for earlier detection of disease; better understanding of warning signs and symptoms)
- Increase the scientific understanding of your own organization regarding the causes and pathophysiology of cardiovascular disease
- Strengthen your organization's ties with national organizations committed to the same goals as your organization

====

==== Collect baseline data on the issues to be addressed

As soon as your organization has a general idea of what it wants to accomplish, the next step is to develop baseline data on the issue to be addressed. Baseline data are the facts and figures that tell you how big the problem is; it gives specific figures about the extent to which it exists in your community.

Baseline data can indicate the incidence (new cases) of a problem in the community. For example, "Malott County has an adolescent pregnancy rate of 12.3 pregnancies for every thousand teenage girls." Such data can also reveal the prevalence (existing cases) of the problem. For example, "In Jefferson County, 35% of teens reported that they did not use contraceptives during the last time they had sex."

Baseline data may also measure community attitudes towards a problem. For example, "65% of the residents of Malott County do not consider teen pregnancy to be an important problem for the community."

===== Why collect baseline data?

This information is important because baseline data provides your organization with the numbers; the starting points against which you can measure how much progress you have made. Not only is this information helpful when originally asking for financial (or other) assistance, it can help you show what your organization has done later in its lifetime.

So, early in your organization's life, you can prove to funders that there really is a very significant problem in your community that needs to be addressed ("Malott County's adolescent pregnancy rate is the highest in the state of Georgia.") Then, when asked later in the life of your community initiative, "What have you done?" you will be able to answer, "Since our coalition was formed, Malott County has seen pregnancy among teens drop by 35%." If you don't collect (or obtain) the baseline information, you can't prove how much you have done.

===== How do you collect this information?

There are two basic ways to collect baseline data:

- You can collect your own baseline data for the information related to your specific issues. Ways to gather this information include the use of surveys, questionnaires, and personal interviews.
- You can use information that has already been collected. Public libraries, city government, social service agencies, local schools, or city health departments may already have the statistics that you want, especially if another organization has already done work on a similar issue in your community.

==== Decide what is realistic for your organization to accomplish

Once you know what you want to do, as well as exactly how big the problem is, it's time to figure out how much you believe your organization can accomplish. Do you have the resources to affect all of the goals you looked at in Step Two? And to what extent will you be able to achieve them?

These questions are difficult ones to answer. It's hard for a new organization to know what it can reasonably expect to get done. For example, if you are trying to increase rates of childhood immunization, will your organization be able to increase it by 5% in three years, or by 20% in one year? How do you make these decisions?

Unfortunately, there are no easy answers. Your organization will need to take a good look at its resources, as well as talk to experts who have a sense of what is not only possible, but likely. For example, you might ask members of organizations who have done similar things, or researchers in your topic area what they believe makes sense.

Remember, you are attempting to set objectives that are both achievable and challenging. It's hard to hit just the right note of balance between these two qualities, and you may not always get it just right. Research and experience, however, should help you come closer and closer to this goal.

==== Set the objectives for your organization or initiative

With all of this information in mind, your organization is ready to set some short-term goals or objectives that are feasible but demanding. Remember, objectives refer to specific measurable results. These changes in behavior, outcome, and process must be able to be tracked and measured in such a way to show that a change has occurred.

Your organization's list of objectives should do all of the following:

- Include all three types of objectives: objectives that measure behavior change, community outcomes, and those that measure important parts of the planning process.
- Include specific objectives that tell how much of what will occur by when. For example, "By 2025, rates of teen pregnancy among 12-17 year old girls will decrease by 30%."
- They should include all of the "SMART + C Criteria." As we discussed earlier in this section, this means that they should be, Specific, Measurable, Achievable, Relevant, Timed, and Challenging.

Let's look at one more example of some objectives; these goals come from an organization focusing on preventing adolescent substance abuse.

====
*Objectives developed by an adolescent substance abuse prevention initiative*

By the year 2024, the use of tobacco among 12-17 year olds will be reduced by 40%.
By the year 2024, the use of alcohol among 12-17 year olds will be reduced by 50%.
By the year 2024, the use of marijuana among 12-17 year olds will be reduced by 70%.
By the year 2024, the use of cocaine among 12-17 year olds will be reduced by 80%.
====

==== Review the objectives your organization has created

Before you finalize your objectives, it makes sense for members of your organization to review them one more time, and possibly, ask people outside of your organization to review them as well. You might ask members of your organization who were not involved in the development process to review your work. You may also wish to get the thoughts of local experts, targets and agents of change, and/or of people doing similar work in other communities to review what you have developed. You can ask reviewers to comment on:

- Do your objectives each meet the criteria of "SMART+ C"?
- Is your list of objectives complete? That is, are there important objectives that are missing?
- Are your objectives appropriate? Are any of your objectives controversial? If so, your organization needs to decide if it is ready to handle the storm that may arise. For example, a program that is trying to reduce the spread of AIDS in its community may decide clean needles for drug addicts is an objective they wish to strive for; but it may very well cause difficulties for that organization. That's not to say the organization shouldn't make that an objective, but they should do so with a clear understanding of the consequences.

==== Use your objectives to define your organization's strategies

Finally, once you have your objectives, you are ready for the next step: developing the strategies that will make them possible. Once your objectives are finished, and satisfactory to members of the organization and important people outside of your group, you are ready to move on to developing successful strategies.

== Checklist


___Your organization understands what objectives are, and when you should develop them

___Your organization understands that objectives should be "SMART +C"

___You have defined and reaffirmed your vision and mission statements

___You have determined the changes to be made

___You have collected baseline data on the issues to be addressed

___You have decided what is realistic for your organization to accomplish

___You have set objectives for the organization or initiative

___You have reviewed the objectives your organization has created

== Tools