= OpenAPI Document Generation
:toc:


== Swagger UI

=== The `docker` way
You can host a Swagger UI mini site with Swagger-ui docker image by specifying your OpenAPI JSON/YAML either through mount volume (`SWAGGER_JSON`) or environment variable `SWAGGER_JSON_URL` for externally hosted file

==== Specifying files on host
The following snippet mounts host directory `/Users/david/code/schemas` to docker volume `apis` and uses `openapi.yaml` in the directory as the default Swagger yaml file.

[source,shell]
----
docker run -p 80:8000 --name openapi \
 -e SWAGGER_JSON=/apis/openapi.yaml \
 -v /Users/david/code/schemas:/apis \
 swaggerapi/swagger-ui:v4.14.0
----

==== Specifying remote files
[source, shellscript]
----
docker run -p 80:8080 --name openapi \
 -e SWAGGER_JSON_URL=https://foo.bar/openapi.yaml \
swaggerapi/swagger-ui:v4.14.0
----

=== GitHub Pages
CAUTION: GitHub Pages only support `public` or `internal` repositories.

The idea is to create an `index.html` page which contains Swagger UI js/css resources. In this file, you can define your OpenAPI file located in your repository.

This method uses traditional GitHub Pages deployment process without using GitHub actions.

==== `index.html`
[source,html]
----
<html>
    <head>
        <!-- Load the latest Swagger UI code and style from npm using unpkg.com -->
        <script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
        <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3/swagger-ui.css"/>
        <title>Environment Consistency API</title>
    </head>
    <body>
        <div id="swagger-ui"></div> <!-- Div to hold the UI component -->
        <script>
            window.onload = function () {
                // Begin Swagger UI call region
                const ui = SwaggerUIBundle({
                    url: "postman/schemas/openapi.yaml", //Location of Open API spec in the repo
                    dom_id: '#swagger-ui',
                    deepLinking: true,
                    presets: [
                        SwaggerUIBundle.presets.apis,
                        SwaggerUIBundle.SwaggerUIStandalonePreset
                    ],
                    plugins: [
                        SwaggerUIBundle.plugins.DownloadUrl
                    ],
                })
                window.ui = ui
            }
        </script>
    </body>
</html>
----


== https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator]


=== Command Line

==== Install the command line

MacOS:: `brew install openapi-generator`


==== Generate HTML2 and asciidoc

HTML2::
+
[source,bash]
----
openapi-generator generate -i openapi.yaml -g html2
----
asciidoc::
+
[source,bash]
----
openapi-generator generate -i openapi.yaml -g asciidoc
----

=== Gradle Plugin
[source, groovy]
----
plugins {
  id "org.openapi.generator" version "6.0.1"
}
----
See more documentation at https://github.com/OpenAPITools/openapi-generator/blob/v6.0.1/modules/openapi-generator-gradle-plugin/README.adoc[OpenAPI Generator Gradle Plugin]

