= jq
:toc:
:icons: font
:source-highlighter: rouge

.icon:book[] jq references
[sidebar]
****
* https://stedolan.github.io/jq/[jq web site]
* https://maas.io/blog/improving-cli-output-with-jq[Improving CLI output with jq]
****

== Cheatsheet

.External sources
[sidebar]
****

* https://gist.github.com/olih/f7437fb6962fb3ee9fe95bda8d2c8fa4[Processing JSON using jq]
****

=== JSON arrays

[cols="30,70"]
|===
|Description|Command
| Query by attribute name|`az account list-locations \| jq -r ".[].name"`
|===

==== data types

with type been arrays, objects, iterables, booleans, numbers, normals, finites, strings, nulls, values, scalars

==== Slicing and Filtering

[cols="30,70"]
|===
|Description|Command
| All
| `jq .[]`

| First
|	`jq '.[0]'`

| Range
| `jq '.[2:4]'`

| First 3
| `jq '.[:3]'`

| Last 2
| `jq '.[-2:]'`

| Before Last
| `jq '.[-2]'`

| Select array of int by value
| `jq 'map(select(. >= 2))'`

| Select array of objects by array item property value
m| `jq '.[] &#124; select(.id == "second")'`

| Select by type
| `jq '.[] &#124; numbers'` ^*^


|List Azure role assignments with principalType == `Group`
m|`az role assignment list --all \| jq '[.[]\|select(.principalType == "Group")]'`

|Filter a property of object array by array item value
|`cat assignments-china.json\| jq '[.assignments[|select(.identityType=="Group") ]'`

|===

===== Filtering an array property by item value
===== Given json

The command below filters values whose `identityType=="Group"`

[source,shell]
----
cat assignments.json| jq '[.assignments[]|select(.identityType=="Group") ]'
----


[source,json]
----
{
    "assignments": [
        {
            "identity": "azure-tenant-admin",
            "identityType": "Group",
            "role": "Contributor",
            "scope": "tenant root",
            "assignment": "PIM"
        },
        {
            "identity": "12345688asdf32",
            "identityType": "ServicePrincipal",
            "role": "Contributor",
            "scope": "Contosoo-root",
            "assignment": "RBAC"
        },
        {
            "identity": "finops",
            "identityType": "Group",
            "role": "Cost Management Contributor",
            "scope": "Contosoo-root",
            "assignment": "RBAC"
        }

    ]
}
----


====== Output

[source,json]
----
[
  {
    "identity": "azure-tenant-admin",
    "identityType": "Group",
    "role": "Contributor",
    "scope": "tenant root",
    "assignment": "PIM"
  },
  {
    "identity": "finops",
    "identityType": "Group",
    "role": "Cost Management Contributor",
    "scope": "Contosoo-root",
    "assignment": "RBAC"
  }
]
----

=== Sum values in an array

To sum all values in `issueCount` field in the following json example, run the jq command below

==== Expression
[source,shell]
----
[.records[].issueCount]|add
----

==== Input
[source,json]
----
{
    "metadata": {
        "totalCount": 195,
        "totalPages": 1,
        "page": 1,
        "pageSize": 195
    },
    "source": "sb1",
    "target": "cnp0",
    "records": [
        {
            "service": "unknown",
            "resultCount": 34,
            "issueCount": 39,
            "commentCount": 0,
            "team": "accounts-identity,cnc,cv-platform,historical,platform-usage,streams,ui"
        },
        {
            "service": "aba-swap-detector",
            "resultCount": 2,
            "issueCount": 2,
            "commentCount": 0,
            "team": "canis-minor"
        },
        {
            "service": "account-service",
            "resultCount": 1,
            "issueCount": 12,
            "commentCount": 0,
            "team": "accounts-identity"
        },
        {
            "service": "assets-account-consistency-monitor",
            "resultCount": 1,
            "issueCount": 1,
            "commentCount": 0,
            "team": "inventory"
        },
        {
            "service": "assets-cache-consistency-monitor",
            "resultCount": 1,
            "issueCount": 1,
            "commentCount": 0,
            "team": "inventory"
        },
        {
            "service": "assets-cache-writer",
            "resultCount": 2,
            "issueCount": 2,
            "commentCount": 0,
            "team": "inventory"
        }
    ]
}
----
==== Output
```
57
```

=== Filter by property in object array

Gets a list of strings from a property from a subset of an object array.

==== Expression

[source, bash]
----
.value[]|select(.mail !=null)|.userPrincipalName|rtrimstr("@example.com")
----

==== Input
[source,json]
----
{
	"@odata.context": "https://microsoftgraph.chinacloudapi.cn/v1.0/$metadata#users(id,userPrincipalName,displayName,accountEnabled,appId,mail,onPremisesSyncEnabled,deviceId)",
	"@odata.count": 292,
	"value": [
		{
			"id": "00d2896d-1cf1-4aa5-8288-55164a29a0a2",
			"userPrincipalName": "FZPY74@example.com",
			"displayName": "Lulu Olson",
			"accountEnabled": true,
			"mail": "FZPY74@example.com",
			"onPremisesSyncEnabled": true
		},
		{
			"id": "016c5530-1cfb-4d8d-9eb3-b67896f72cbe",
			"userPrincipalName": "NZJFV1@example.com",
			"displayName": "Franklin McGee",
			"accountEnabled": true,
			"mail": null,
			"onPremisesSyncEnabled": true
		},
		{
			"id": "017f6ae3-c7f1-4fb7-8050-8f88097b2b7b",
			"userPrincipalName": "NZ8P8N@example.com",
			"displayName": "Agnes Gill",
			"accountEnabled": true,
			"mail": "NZ8P8N@example.com",
			"onPremisesSyncEnabled": true
		},
		{
			"id": "01d1566f-d4ef-433a-8480-d7272d640e41",
			"userPrincipalName": "NZD0L1@example.com",
			"displayName": "Cecelia Casey",
			"accountEnabled": true,
			"mail": "NZD0L1@example.com",
			"onPremisesSyncEnabled": true
		},
		{
			"id": "03180156-9719-4950-baef-4e2baa679f10",
			"userPrincipalName": "RZGF6Q@example.com",
			"displayName": "Cameron Norris",
			"accountEnabled": true,
			"mail": "RZGF6Q@example.com",
			"onPremisesSyncEnabled": true
		},
		{
			"id": "03fbe4ba-b87c-47d6-bd32-28f00d29f7ff",
			"userPrincipalName": "BZHQ0G@example.com",
			"displayName": "Rex Flores",
			"accountEnabled": true,
			"mail": null,
			"onPremisesSyncEnabled": true
		},
		{
			"id": "05e44699-3292-4bef-a4f1-636c1fa991e4",
			"userPrincipalName": "KZ51WZ@example.com",
			"displayName": "Leila Bailey",
			"accountEnabled": true,
			"mail": "KZ51WZ@example.com",
			"onPremisesSyncEnabled": true
		}
	]
}
----

==== Output
[source,bash]
----
"FZPY74"
"NZ8P8N"
"NZD0L1"
"RZGF6Q"
"KZ51WZ"
----
