= jq
:toc:
:icons: font
:source-highlighter: rouge

.icon:book[] jq references
[sidebar]
****
* https://stedolan.github.io/jq/[jq web site]
****

== Cheatsheet

.External sources
[sidebar]
****

* https://gist.github.com/olih/f7437fb6962fb3ee9fe95bda8d2c8fa4[Processing JSON using jq]
****

=== JSON arrays

[cols="30,70"]
|===
|Description|Command
| Query by attribute name|`az account list-locations \| jq -r ".[].name"`
|===

===== data types

with type been arrays, objects, iterables, booleans, numbers, normals, finites, strings, nulls, values, scalars

==== Slicing and Filtering

[cols="30,70"]
|===
|Description|Command
| All
| `jq .[]`

| First
|	`jq '.[0]'`

| Range
| `jq '.[2:4]'`

| First 3
| `jq '.[:3]'`

| Last 2
| `jq '.[-2:]'`

| Before Last
| `jq '.[-2]'`

| Select array of int by value
| `jq 'map(select(. >= 2))'`

| Select array of objects by array item property value
m| `jq '.[] &#124; select(.id == "second")'`

| Select by type
| `jq '.[] &#124; numbers'` ^*^


|List Azure role assignments with principalType == `Group`
m|`az role assignment list --all | jq '.[]|select(.principalType == "Group")'`

|===

=== Sum values in an array

To sum all values in `issueCount` field in the following json example, run the jq command below

[source,shell]
----
cat example.json| jq "[.records[].issueCount]|add"
----

[source,json]
----
{
    "metadata": {
        "totalCount": 195,
        "totalPages": 1,
        "page": 1,
        "pageSize": 195
    },
    "source": "sb1",
    "target": "cnp0",
    "records": [
        {
            "service": "unknown",
            "resultCount": 34,
            "issueCount": 39,
            "commentCount": 0,
            "team": "accounts-identity,cnc,cv-platform,historical,platform-usage,streams,ui"
        },
        {
            "service": "aba-swap-detector",
            "resultCount": 2,
            "issueCount": 2,
            "commentCount": 0,
            "team": "canis-minor"
        },
        {
            "service": "account-service",
            "resultCount": 1,
            "issueCount": 12,
            "commentCount": 0,
            "team": "accounts-identity"
        },
        {
            "service": "assets-account-consistency-monitor",
            "resultCount": 1,
            "issueCount": 1,
            "commentCount": 0,
            "team": "inventory"
        },
        {
            "service": "assets-cache-consistency-monitor",
            "resultCount": 1,
            "issueCount": 1,
            "commentCount": 0,
            "team": "inventory"
        },
        {
            "service": "assets-cache-writer",
            "resultCount": 2,
            "issueCount": 2,
            "commentCount": 0,
            "team": "inventory"
        }
    ]
}
----