= Developing Successful Strategies: Planning to Win
:toc:

== What is a strategy?

A strategy is a way of describing _how_ you are going to get things done. It is less specific than an action plan (which tells the who-what-when); instead, it tries to broadly answer the question, "How do we get there from here?" (Do we want to take the train? Fly? Walk?)

A good strategy will take into account existing barriers and resources (people, money, power, materials, etc.). It will also stay with the overall vision, mission, and objectives of the initiative. Often, an initiative will use many different strategies--providing information, enhancing support, removing barriers, providing resources, etc.--to achieve its goals.

Objectives outline the aims of an initiative--what success would look like in achieving the vision and mission. By contrast, strategies suggest paths to take (and how to move along) on the road to success. That is, strategies help you determine how you will realize your vision and objectives through the nitty-gritty world of action.

== What are the criteria for developing a good strategy?

Strategies for your community initiative should meet several criteria.

Does the strategy:

- _Give overall direction_? A strategy, such as enhancing experience and skill or increasing resources and opportunities, should point out the overall path without dictating a particular narrow approach (e.g., using a specific skills training program).
- _Fit resources and opportunities_? A good strategy takes advantage of current resources and assets, such as people's willingness to act or a tradition of self-help and community pride. It also embraces new opportunities such as an emerging public concern for neighborhood safety or parallel economic development efforts in the business community.
- _Minimize resistance and barriers_? When initiatives set out to accomplish important things, resistance (even opposition) is inevitable. However, strategies need not provide a reason for opponents to attack the initiative. Good strategies attract allies and deter opponents.
- _Reach those affected_? To address the issue or problem, strategies must connect the intervention with those who it should benefit. For example, if the mission of the initiative is to get people into decent jobs, do the strategies (providing education and skills training, creating job opportunities, etc.) reach those currently unemployed?
- _Advance the mission_? Taken together, are strategies likely to make a difference on the mission and objectives? If the aim is to reduce a problem such as unemployment, are the strategies enough to make a difference on rates of employment? If the aim is to prevent a problem, such as substance abuse, have factors contributing to risk (and protection) been changed sufficiently to reduce use of alcohol, tobacco, and other drugs?

== Why develop strategies?

Developing strategies is really a way to focus your efforts and figure out how you're going to get things done. By doing so, you can achieve the following advantages:

- Taking advantage of resources and emerging opportunities
- Responding effectively to resistance and barriers
- A more efficient use of time, energy, and resources

== When should you develop strategies for your initiative?

Developing strategies is the fourth step in the VMOSA (Vision, Mission, Objectives, Strategies, and Action Plans) process outlined at the beginning of this chapter. Developing strategies is the essential step between figuring out your objectives and making the changes to reach them. Strategies should always be formed in advance of taking action, not deciding how to do something after you have done it. Without a clear idea of the how, your group's actions may waste time and effort and fail to take advantage of emerging opportunities. Strategies should also be updated periodically to meet the needs of a changing environment, including new opportunities and emerging opposition to the group's efforts.

== How do you develop strategies?

Once again, let's refer back to our friends at the fictional Reducing the Risk (RTR) Coalition that hopes to reduce the risk of teenage pregnancy in its community. We'll walk through the process of developing strategies with this group so as to better explain the who, what, and why of strategies.

As with the process you went through to write your vision and mission statements and to set your objectives, developing strategies involves brainstorming and talking to community members.

=== Organize a brainstorming meeting with members of your organization and members of the community

Remember, people will work best in a relaxed and welcoming environment. You can help achieve this by:

- Making meetings a place where all members feel that their ideas are listened to and valued, and where constructive criticism may be openly voiced. To help meet these goals, you might post some "ground rules" so people feel free to express themselves. Ground rules might include:
* One person speaks at a time
* No interrupting each other
* Everyone's ideas are respected
- Bringing fans or heaters (if needed) so people will be comfortable.
- Asking members to escort each other home or to their cars, the subway, or the bus stop if the meeting runs late.
- Providing refreshments. Never underestimate the power of homemade food, drinks, and other treats.

The RTR Coalition held brainstorming sessions among organization members. They invited local teens, parents, teachers, counselors, church members, and other community leaders to participate in listening sessions. These were used to help develop strategies to reduce the risk of teen pregnancy. Homemade cookies, fruit, and coffee helped make participants feel welcome.

=== Review (identify) the targets and agents of change for your initiative

- Your targets of change include all of the people who experience (or are at risk for) this issue or problem addressed by your initiative. Remember to be inclusive; that is, include everyone who is affected by the problem or issue or whose action or inaction contributes to it. For example, a coalition such the RTR Coalition would want to include all teenagers as potential targets of change, not just adolescents who seem particularly at risk, and parents, peers, and teachers whose actions or inactions might make a difference.
- Your agents of change include everyone who is in a position to help contribute to the solution. With the RTR Coalition, examples of agents of change might include teens, teachers, guidance counselors, parents of teens, lawmakers, and others.

=== Review your vision, mission, and objectives to keep you on the right track

It is helpful to review your mission, vision, and objectives to ensure that your strategies are all aligned with the goals expressed in your previous work.

=== Work together to brainstorm the best strategies for your initiative

The following list of questions can be a guide for deciding on the most beneficial strategies for your group:

- What resources and assets exist that can be used to help achieve the vision and mission? How can they be used best?
- What obstacles or resistance exist that could make it difficult to achieve your vision and mission? How can you minimize or get around them?
- What are potential agents of change willing to do to serve the mission?
- Do you want to reduce the existing problem, or does it make more sense to try to prevent (or reduce risk for) problems before they start? For example, if you are trying to reduce teen sexual activity, you might consider gearing some of your strategies to younger children, for whom sex is not yet a personal issue; or, to promote academic success, to work with younger children who still have full potential for learning and school success.
- How will your potential strategies decrease the risk for experiencing the problem (e.g., young girls getting pressure for sex from older men)? How will the strategies increase protective factors (e.g., support from peers; access to contraceptives)?
- What potential strategies will affect the whole population and problem? For example, connecting youth with caring adults might be good for virtually all youth, regardless of income or past experience with the problem. Also, just one strategy, affecting just one part of the community such as schools or youth organizations, often isn't enough to improve the situation. Make sure that your strategies affect the problem or issue as a whole.
- What potential strategies reach those at particular risk for the problem? For example, early screenings might help focus on those at higher risk for heart disease or cancer; past academic failure or history of drug use, for identifying with whom support and other intervention efforts might be focused.

Let's look at the strategies proposed by the members of the RTR Coalition to prevent teen pregnancy.

.The strategies of the RTR Coalition
====
We will pursue the following strategies to reach each of our objectives:

- Assist local churches in implementing parent-child awareness sessions (for example, a series of talks might be given discussing how to talk to your preteen about sex);
- Include comprehensive sex education in the curriculum of students from kindergarten through grade twelve, including information on abstinence, sexual decision-making skills, and family planning / contraception at age-appropriate times;
- Incorporate options for teacher-led and peer support programs in the schools;
- Survey and report on student knowledge, attitudes, and behavior related to sexual issues;
- Increase access to contraception;
- Organize a school/community action group to create supervised after-school activities, mentor programs, etc.
====

Things to note about the RTR strategies:

- They give overall direction (without dictating specifics, such as the particular sexuality education curricula to be used).
- They fit local resources, including a variety of the available agents of change (in this case, peers, parents and guardians, clergy, and teachers).
- Some of the strategies try to change existing situations (such as increased access to contraception); others are geared to stop the problem of teen pregnancy before it starts (for example, assisting local churches to improve early parent-child communication).
- The strategies involve many different parts of the community, including churches and other groups from whom opposition to some strategies (such as access to contraceptives) might be expected.
- The strategies try to decrease some of the probable risk factors for teen pregnancy (lack of information, lack of access to contraceptives, peer pressure), and at the same time, they try to increase some of the possible protective factors (increased parent-child communication, church involvement, education, opportunities for a better future).

== Checklist


Develop successful strategies:

___You can form a planning group to develop strategies

Find potential members:

___Community leaders

___Members of other local organizations

___Those affected by the issue or problem

___Representatives of local ethnic and cultural groups

Create a supportive environment:

___A safe and comfortable building, neighborhood site

___Create an open forum for all to participate

Determine/review targets and agents of change:

___Be inclusive of those experiences, at risk for, and contributing to the issue

___Determine risk and protective factors affecting the issue

___Review vision, mission, and objectives

Brainstorm the best strategies:

___Determine potential obstacles

___Strategize to get around obstacles

___Identify how agents of change will help

___Decide when strategies will affect targets of change

___Determine if you will work on repairing or preventing problems

___Ensure strategies decrease risk factors, and increase protective factors

___Make sure strategies will address entire problem or issue

Do the strategies meet the criteria?

___Give overall direction

___Fit resources and opportunities

___Minimize resistance and barriers

___Reach those affected

___Advance the mission
