= Developing an Action Plan
:toc:

IMPORTANT: The information in this page is not complete. See more information at https://ctb.ku.edu/en/table-of-contents/structure/strategic-planning/develop-action-plans/main[Section 5. Developing an Action Plan]

Developing an action plan can help changemakers turn their visions into reality, and increase efficiency and accountability within an organization. An action plan describes the way your organization will meet its objectives through detailed action steps that describe how and when these steps will be taken. This section provides a guide for developing and utilizing your group's action plan.

== What is an action plan?

In some ways, an action plan is a "heroic" act: it helps us turn our dreams into a reality. An action plan is a way to make sure your organization's vision is made concrete. It describes the way your group will use its strategies to meet its objectives. An action plan consists of a number of action steps or changes to be brought about in your community.

Each action step or change to be sought should include the following information:

- *What* actions or changes will occur
- *Who* will carry out these changes
- *By when* they will take place, and for how long
- *What resources* (i.e., money, staff) are needed to carry out these changes
- *Communication* (who should know what?)

== What are the criteria for a good action plan?

The action plan for your initiative should meet several criteria.

Is the action plan:

- _Complete_? Does it list all the action steps or changes to be sought in all relevant parts of the community (e.g., schools, business, government, faith community)?
- _Clear_? Is it apparent who will do what by when?
- _Current_? Does the action plan reflect the current work? Does it anticipate newly emerging opportunities and barriers?

== Why should you develop an action plan?

There is an inspirational adage that says, "People don't plan to fail. Instead they fail to plan." Because you certainly don't want to fail, it makes sense to take all of the steps necessary to ensure success, including developing an action plan.

There are lots of good reasons to work out the details of your organization's work in an action plan, including:

- To lend credibility to your organization. An action plan shows members of the community (including grantmakers) that your organization is well ordered and dedicated to getting things done.
- To be sure you don't overlook any of the details
- To understand what is and isn't possible for your organization to do
- For efficiency: to save time, energy, and resources in the long run
- For accountability: To increase the chances that people will do what needs to be done

== When should you create an action plan?

Ideally, an action plan should be developed within the first six months to one year of the start of an organization. It is developed after you have determined the vision, mission, objectives, and strategies of your group. If you develop an action plan when you are ready to start getting things done, it will give you a blueprint for running your organization or initiative.

Remember, though, that an action plan is always a work in progress. It is not something you can write, lock in your file drawers, and forget about. Keep it visible. Display it prominently. As your organization changes and grows, you will want to continually (usually monthly) revise your action plan to fit the changing needs of your group and community.

== How to write an action plan
=== Determine what people and sectors of the community should be changed and involved in finding solutions

If you have been using the VMOSA (Vision, Mission, Objectives, Strategies, Action Plans) model, you might have already done this, when you were deciding upon your group's objectives. Again, try to be inclusive. Most of the health and development issues that community partnerships deal with are community-wide, and thus need a community-wide solution. Possible sectors include the media, the business community, religious organizations, schools, youth organizations, social service organizations, health organizations, and others.

Some members of the community you might consider asking to join the action planning group include:

- Influential people from all the parts of the community affected by your initiative (e.g., from churches and synagogues, the school system, law enforcement, etc.)
- People who are directly involved in the problem (e.g., local high school students and their parents might be involved in planning a coalition trying to reduce teen substance abuse)
- Members of grassroots organizations
- Members of the various ethnic and cultural groups in your community
- People you know who are interested in the problem or issue
- Newcomers or young people in the community who are not yet involved

